-- ============================================================================
-- 02_employees_core.sql
-- ----------------------------------------------------------------------------
-- Consolidated from legacy migrations: 002, 017, 030, 034, 035, 042, 049, 053
-- Apply order: run this file in the same numeric order as the file name.
-- Generated by scripts/build-migrations-v2.ps1 â€” DO NOT EDIT BY HAND.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SOURCE: 002_employees.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 002_employees.sql
-- Employees, salary history, change requests, documents
-- ============================================================

CREATE TABLE IF NOT EXISTS public.employees (
    id              text PRIMARY KEY,
    profile_id      uuid UNIQUE REFERENCES public.profiles(id) ON DELETE SET NULL,
    name            text NOT NULL,
    email           text NOT NULL,
    role            text NOT NULL DEFAULT 'Employee',
    department      text NOT NULL DEFAULT '',
    status          text NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active','inactive','resigned')),
    work_type       text NOT NULL DEFAULT 'WFO'
                    CHECK (work_type IN ('WFH','WFO','HYBRID','ONSITE')),
    salary          numeric NOT NULL DEFAULT 0,
    join_date       date NOT NULL DEFAULT CURRENT_DATE,
    productivity    integer NOT NULL DEFAULT 0,
    location        text NOT NULL DEFAULT '',
    phone           text,
    birthday        date,
    team_leader     text,
    avatar_url      text,
    pin             text,
    nfc_id          text,
    resigned_at     timestamptz,
    shift_id        text,
    pay_frequency   text CHECK (pay_frequency IN ('monthly','semi_monthly','bi_weekly','weekly') OR pay_frequency IS NULL),
    work_days       text[],
    whatsapp_number text,
    preferred_channel text CHECK (preferred_channel IN ('email','whatsapp','sms','in_app') OR preferred_channel IS NULL),
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_employees_status ON public.employees(status);
CREATE INDEX IF NOT EXISTS idx_employees_department ON public.employees(department);
CREATE INDEX IF NOT EXISTS idx_employees_profile_id ON public.employees(profile_id);

ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS set_employees_updated_at ON public.employees;
CREATE TRIGGER set_employees_updated_at
    BEFORE UPDATE ON public.employees
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Salary Change Requests (HR proposes, Finance approves)
CREATE TABLE IF NOT EXISTS public.salary_change_requests (
    id              text PRIMARY KEY,
    employee_id     text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    old_salary      numeric NOT NULL,
    proposed_salary numeric NOT NULL,
    effective_date  date NOT NULL,
    reason          text NOT NULL,
    proposed_by     text NOT NULL,
    proposed_at     timestamptz NOT NULL DEFAULT now(),
    status          text NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','approved','rejected')),
    reviewed_by     text,
    reviewed_at     timestamptz
);

CREATE INDEX IF NOT EXISTS idx_salary_requests_employee ON public.salary_change_requests(employee_id);
CREATE INDEX IF NOT EXISTS idx_salary_requests_status ON public.salary_change_requests(status);

ALTER TABLE public.salary_change_requests ENABLE ROW LEVEL SECURITY;

-- Salary History (immutable audit trail)
CREATE TABLE IF NOT EXISTS public.salary_history (
    id              text PRIMARY KEY,
    employee_id     text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    monthly_salary  numeric NOT NULL,
    effective_from  date NOT NULL,
    effective_to    date,
    approved_by     text NOT NULL,
    reason          text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_salary_history_employee ON public.salary_history(employee_id);

ALTER TABLE public.salary_history ENABLE ROW LEVEL SECURITY;

-- Employee Documents
CREATE TABLE IF NOT EXISTS public.employee_documents (
    id          text PRIMARY KEY,
    employee_id text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    name        text NOT NULL,
    file_url    text,
    uploaded_at timestamptz NOT NULL DEFAULT now(),
    deleted_at  timestamptz
);

CREATE INDEX IF NOT EXISTS idx_employee_docs_employee ON public.employee_documents(employee_id);

ALTER TABLE public.employee_documents ENABLE ROW LEVEL SECURITY;


-- ----------------------------------------------------------------------------
-- SOURCE: 017_align_employee_roles.sql
-- ----------------------------------------------------------------------------
-- ════════════════════════════════════════════════════════════════════
-- 017: Align employees.role with profiles.role (lowercase)
-- Run this in Supabase Dashboard > SQL Editor
-- ════════════════════════════════════════════════════════════════════

-- Step 1: Drop old constraint
ALTER TABLE public.employees DROP CONSTRAINT IF EXISTS employees_role_check;

-- Step 2: Migrate existing data to lowercase
UPDATE public.employees SET role = 'admin' WHERE role = 'Admin';
UPDATE public.employees SET role = 'hr' WHERE role = 'HR Admin';
UPDATE public.employees SET role = 'finance' WHERE role = 'Finance';
UPDATE public.employees SET role = 'employee' WHERE role = 'Employee';
UPDATE public.employees SET role = 'supervisor' WHERE role = 'Supervisor';
UPDATE public.employees SET role = 'payroll_admin' WHERE role = 'Payroll Admin';
UPDATE public.employees SET role = 'auditor' WHERE role = 'Auditor';

-- Step 3: Add new constraint (lowercase, matching profiles.role + frontend Role type)
ALTER TABLE public.employees ADD CONSTRAINT employees_role_check
  CHECK (role IN ('admin','hr','finance','employee','supervisor','payroll_admin','auditor'));


-- ----------------------------------------------------------------------------
-- SOURCE: 030_employees_add_contact_fields.sql
-- ----------------------------------------------------------------------------
-- Migration 030: Add emergency_contact and address columns to employees table
-- These fields already exist in profiles; adding them to employees ensures
-- the write-through sync pattern (Zustand → employees table) maps correctly.

ALTER TABLE public.employees
  ADD COLUMN IF NOT EXISTS emergency_contact text,
  ADD COLUMN IF NOT EXISTS address text;

-- Backfill from profiles where linked
UPDATE public.employees e
SET
  emergency_contact = COALESCE(e.emergency_contact, p.emergency_contact),
  address           = COALESCE(e.address, p.address)
FROM public.profiles p
WHERE e.profile_id::uuid = p.id
  AND (e.emergency_contact IS NULL OR e.address IS NULL);


-- ----------------------------------------------------------------------------
-- SOURCE: 034_job_titles.sql
-- ----------------------------------------------------------------------------
-- ─── Job Titles Table ──────────────────────────────────────────
-- Admin-managed registry of job titles (roles) that can be assigned
-- to employees. Each title has a display name, optional description,
-- department association, and whether it's a leadership position.

CREATE TABLE IF NOT EXISTS public.job_titles (
    id          text        PRIMARY KEY,
    name        text        NOT NULL UNIQUE,
    description text,
    department  text,
    is_active   boolean     NOT NULL DEFAULT true,
    is_lead     boolean     NOT NULL DEFAULT false,
    color       text        NOT NULL DEFAULT '#6366f1',
    created_by  text        NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- RLS: Full access for authenticated users (admin manages in UI)
ALTER TABLE public.job_titles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read job_titles"
    ON public.job_titles FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Authenticated users can insert job_titles"
    ON public.job_titles FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "Authenticated users can update job_titles"
    ON public.job_titles FOR UPDATE
    TO authenticated
    USING (true);

CREATE POLICY "Authenticated users can delete job_titles"
    ON public.job_titles FOR DELETE
    TO authenticated
    USING (true);

-- Index for quick name lookups / auto-complete
CREATE INDEX IF NOT EXISTS idx_job_titles_name ON public.job_titles (lower(name));

-- Index for department filtering
CREATE INDEX IF NOT EXISTS idx_job_titles_department ON public.job_titles (department);

-- Seed with default job titles from the app
INSERT INTO public.job_titles (id, name, department, is_lead, created_by) VALUES
    ('jt_frontend_dev', 'Frontend Developer', 'Engineering', false, 'system'),
    ('jt_backend_dev', 'Backend Developer', 'Engineering', false, 'system'),
    ('jt_uiux_designer', 'UI/UX Designer', 'Design', false, 'system'),
    ('jt_product_manager', 'Product Manager', 'Operations', true, 'system'),
    ('jt_hr_manager', 'HR Manager', 'Human Resources', true, 'system'),
    ('jt_hr_specialist', 'HR Specialist', 'Human Resources', false, 'system'),
    ('jt_finance_manager', 'Finance Manager', 'Finance', true, 'system'),
    ('jt_accountant', 'Accountant', 'Finance', false, 'system'),
    ('jt_marketing_lead', 'Marketing Lead', 'Marketing', true, 'system'),
    ('jt_sales_exec', 'Sales Executive', 'Sales', false, 'system'),
    ('jt_devops_engineer', 'DevOps Engineer', 'Engineering', false, 'system'),
    ('jt_qa_engineer', 'QA Engineer', 'Engineering', false, 'system')
ON CONFLICT (id) DO NOTHING;


-- ----------------------------------------------------------------------------
-- SOURCE: 035_departments.sql
-- ----------------------------------------------------------------------------
-- ─── Departments Table ──────────────────────────────────────────
-- Admin-managed registry of departments/teams within the organization.
-- Each department has a name, optional description, head (manager),
-- and color for visual distinction.

CREATE TABLE IF NOT EXISTS public.departments (
    id          text        PRIMARY KEY,
    name        text        NOT NULL UNIQUE,
    description text,
    head_id     text,       -- employee ID of department head (optional)
    color       text        NOT NULL DEFAULT '#6366f1',
    is_active   boolean     NOT NULL DEFAULT true,
    created_by  text        NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- RLS: Full access for authenticated users (admin manages in UI)
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read departments"
    ON public.departments FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Authenticated users can insert departments"
    ON public.departments FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "Authenticated users can update departments"
    ON public.departments FOR UPDATE
    TO authenticated
    USING (true);

CREATE POLICY "Authenticated users can delete departments"
    ON public.departments FOR DELETE
    TO authenticated
    USING (true);

-- Index for quick name lookups / auto-complete
CREATE INDEX IF NOT EXISTS idx_departments_name ON public.departments (lower(name));

-- Seed with default departments from the app
INSERT INTO public.departments (id, name, description, created_by) VALUES
    ('dept_engineering', 'Engineering', 'Software development and technical teams', 'system'),
    ('dept_design', 'Design', 'UI/UX and graphic design teams', 'system'),
    ('dept_marketing', 'Marketing', 'Marketing and brand management', 'system'),
    ('dept_hr', 'Human Resources', 'HR, recruitment, and employee relations', 'system'),
    ('dept_finance', 'Finance', 'Accounting, payroll, and financial operations', 'system'),
    ('dept_sales', 'Sales', 'Sales and business development', 'system'),
    ('dept_operations', 'Operations', 'Business operations and administration', 'system')
ON CONFLICT (id) DO NOTHING;


-- ----------------------------------------------------------------------------
-- SOURCE: 042_employees_add_job_title.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 042_employees_add_job_title.sql
-- Add job_title column to employees table to store the display title
-- ============================================================

-- Add job_title column to employees table
ALTER TABLE public.employees
ADD COLUMN IF NOT EXISTS job_title text;

-- Create index for job title filtering
CREATE INDEX IF NOT EXISTS idx_employees_job_title ON public.employees(job_title);

-- Comment for documentation
COMMENT ON COLUMN public.employees.job_title IS 'Display job title/position (e.g., "DevOps Engineer", "HR Manager")';


-- ----------------------------------------------------------------------------
-- SOURCE: 049_employees_notification_preferences.sql
-- ----------------------------------------------------------------------------
-- Add notification_preferences jsonb column to employees table.
-- Stores per-employee opt-outs: { leaveUpdates, absenceAlerts, payrollAlerts, pushEnabled }
-- Defaults to empty object (all enabled by default in app code).
ALTER TABLE public.employees
  ADD COLUMN IF NOT EXISTS notification_preferences jsonb NOT NULL DEFAULT '{}'::jsonb;

-- Allow any authenticated user to read/write their own notification_preferences.
-- The API route validates ownership server-side.


-- ----------------------------------------------------------------------------
-- SOURCE: 053_employees_biometric_id.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 053_employees_biometric_id.sql
-- Link HRMS employees to the physical biometric scanner user ID
-- ============================================================

ALTER TABLE public.employees
    ADD COLUMN IF NOT EXISTS biometric_id text;

CREATE UNIQUE INDEX IF NOT EXISTS idx_employees_biometric_id_unique
    ON public.employees (biometric_id)
    WHERE biometric_id IS NOT NULL AND biometric_id <> '';

