-- ============================================================================
-- 03_roles_and_permissions.sql
-- ----------------------------------------------------------------------------
-- Consolidated from legacy migrations: 003, 018, 059
-- Apply order: run this file in the same numeric order as the file name.
-- Generated by scripts/build-migrations-v2.ps1 â€” DO NOT EDIT BY HAND.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SOURCE: 003_roles_permissions.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 003_roles_permissions.sql
-- Custom roles with permission arrays
-- ============================================================

CREATE TABLE IF NOT EXISTS public.roles_custom (
    id          text PRIMARY KEY,
    name        text NOT NULL,
    slug        text NOT NULL UNIQUE,
    color       text NOT NULL DEFAULT '#6366f1',
    icon        text NOT NULL DEFAULT 'Shield',
    is_system   boolean NOT NULL DEFAULT false,
    permissions text[] NOT NULL DEFAULT '{}',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.roles_custom ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS set_roles_custom_updated_at ON public.roles_custom;
CREATE TRIGGER set_roles_custom_updated_at
    BEFORE UPDATE ON public.roles_custom
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Seed the 7 system roles with their default permissions
INSERT INTO public.roles_custom (id, name, slug, color, icon, is_system, permissions) VALUES
('role-admin', 'Administrator', 'admin', '#ef4444', 'ShieldCheck', true, ARRAY[
    'page:dashboard','page:employees','page:attendance','page:leave','page:payroll',
    'page:loans','page:projects','page:reports','page:kiosk','page:notifications',
    'page:audit','page:settings','page:timesheets','page:tasks','page:messages',
    'employees:view','employees:create','employees:edit','employees:delete',
    'employees:view_salary','employees:approve_salary',
    'attendance:view_all','attendance:edit','attendance:approve_overtime',
    'leave:view_all','leave:approve','leave:manage_policies',
    'payroll:view_all','payroll:generate','payroll:lock','payroll:issue','payroll:view_own',
    'loans:view_all','loans:approve','loans:view_own',
    'audit:view','settings:roles','settings:organization','settings:shifts','settings:page_builder',
    'projects:manage','reports:view','reports:government','notifications:manage',
    'timesheets:view_all','timesheets:approve',
    'tasks:view','tasks:create','tasks:assign','tasks:verify','tasks:delete','tasks:manage_groups',
    'messages:send_announcement','messages:manage_channels','messages:send_whatsapp','messages:send_email'
]),
('role-hr', 'HR Admin', 'hr', '#3b82f6', 'Users', true, ARRAY[
    'page:dashboard','page:employees','page:attendance','page:leave','page:reports',
    'page:timesheets','page:settings','page:tasks','page:messages',
    'employees:view','employees:create','employees:edit','employees:delete','employees:view_salary',
    'attendance:view_all','attendance:edit','attendance:approve_overtime',
    'leave:view_all','leave:approve','leave:manage_policies',
    'settings:organization','settings:shifts',
    'reports:view','timesheets:view_all','timesheets:approve',
    'tasks:view','tasks:create','tasks:assign','tasks:verify','tasks:delete','tasks:manage_groups',
    'messages:send_announcement','messages:manage_channels'
]),
('role-finance', 'Finance', 'finance', '#f59e0b', 'Banknote', true, ARRAY[
    'page:dashboard','page:payroll','page:loans','page:reports','page:employees',
    'employees:view','employees:view_salary','employees:approve_salary',
    'payroll:view_all','payroll:generate','payroll:lock','payroll:issue',
    'loans:view_all','loans:approve',
    'reports:view','reports:government'
]),
('role-employee', 'Employee', 'employee', '#8b5cf6', 'User', true, ARRAY[
    'page:dashboard','page:attendance','page:leave','page:payroll','page:tasks','page:messages',
    'payroll:view_own','loans:view_own',
    'tasks:view'
]),
('role-supervisor', 'Supervisor', 'supervisor', '#f97316', 'UserCheck', true, ARRAY[
    'page:dashboard','page:employees','page:attendance','page:leave',
    'page:timesheets','page:projects','page:tasks','page:messages',
    'employees:view','employees:view_salary',
    'attendance:view_all','attendance:approve_overtime',
    'leave:view_all','leave:approve',
    'timesheets:view_all','timesheets:approve',
    'projects:manage',
    'tasks:view','tasks:create','tasks:assign','tasks:verify','tasks:manage_groups',
    'messages:send_announcement','messages:manage_channels'
]),
('role-payroll-admin', 'Payroll Admin', 'payroll_admin', '#14b8a6', 'Calculator', true, ARRAY[
    'page:dashboard','page:payroll','page:loans','page:reports','page:timesheets',
    'payroll:view_all','payroll:generate','payroll:lock','payroll:issue',
    'loans:view_all','loans:approve',
    'reports:view','reports:government',
    'timesheets:view_all','timesheets:approve'
]),
('role-auditor', 'Auditor', 'auditor', '#64748b', 'Eye', true, ARRAY[
    'page:dashboard','page:audit','page:reports','page:employees',
    'employees:view','audit:view','reports:view'
])
ON CONFLICT (slug) DO NOTHING;


-- ----------------------------------------------------------------------------
-- SOURCE: 018_seed_profile_flags.sql
-- ----------------------------------------------------------------------------
-- Ensure all seed/demo accounts are fully onboarded.
-- profile_complete=true prevents the onboarding modal from triggering.
-- must_change_password=false prevents the forced password change step.
UPDATE profiles
SET profile_complete = true,
    must_change_password = false
WHERE profile_complete = false
   OR must_change_password = true;


-- ----------------------------------------------------------------------------
-- SOURCE: 059_fix_account_role_sync.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 059_fix_account_role_sync.sql
-- Ensure newly created auth users keep intended system role
-- and repair existing profile/employee role mismatches.
-- ============================================================

-- 1) Harden auth->profile trigger role mapping.
-- Prefer explicit role from user/app metadata, normalize to lowercase,
-- and fall back to employee only for unknown/empty values.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  requested_role text;
BEGIN
  requested_role := lower(
    coalesce(
      nullif(NEW.raw_user_meta_data->>'role', ''),
      nullif(NEW.raw_app_meta_data->>'role', ''),
      'employee'
    )
  );

  IF requested_role NOT IN ('admin','hr','finance','employee','supervisor','payroll_admin','auditor') THEN
    requested_role := 'employee';
  END IF;

  INSERT INTO public.profiles (id, name, email, role)
  VALUES (
    NEW.id,
    coalesce(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    NEW.email,
    requested_role
  )
  ON CONFLICT (id) DO UPDATE
    SET name = EXCLUDED.name,
        email = EXCLUDED.email,
        role = EXCLUDED.role;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Ensure trigger points to latest function definition.
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

-- 2) One-time repair: profile role should match linked employee role.
UPDATE public.profiles p
SET role = e.role
FROM public.employees e
WHERE e.profile_id = p.id
  AND e.role IN ('admin','hr','finance','employee','supervisor','payroll_admin','auditor')
  AND p.role IS DISTINCT FROM e.role;

