-- ============================================================================
-- 04_attendance_and_kiosk.sql
-- ----------------------------------------------------------------------------
-- Consolidated from legacy migrations: 004, 022, 023, 025, 026, 033, 041, 051
-- Apply order: run this file in the same numeric order as the file name.
-- Generated by scripts/build-migrations-v2.ps1 â€” DO NOT EDIT BY HAND.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SOURCE: 004_attendance.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 004_attendance.sql
-- Attendance: events (append-only), evidence, exceptions,
-- computed logs, shifts, holidays, overtime, penalties
-- ============================================================

-- Attendance Events — APPEND-ONLY immutable ledger (§2)
CREATE TABLE IF NOT EXISTS public.attendance_events (
    id              text PRIMARY KEY,
    employee_id     text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    event_type      text NOT NULL CHECK (event_type IN ('IN','OUT','BREAK_START','BREAK_END')),
    timestamp_utc   timestamptz NOT NULL,
    project_id      text,
    device_id       text,
    created_at      timestamptz NOT NULL DEFAULT now()
);

-- IMPORTANT: No UPDATE or DELETE policies will be created for this table (immutable)
CREATE INDEX IF NOT EXISTS idx_att_events_employee ON public.attendance_events(employee_id);
CREATE INDEX IF NOT EXISTS idx_att_events_date ON public.attendance_events(timestamp_utc);

ALTER TABLE public.attendance_events ENABLE ROW LEVEL SECURITY;

-- Attendance Evidence — verification proof per clock event
CREATE TABLE IF NOT EXISTS public.attendance_evidence (
    id                      text PRIMARY KEY,
    event_id                text NOT NULL REFERENCES public.attendance_events(id) ON DELETE CASCADE,
    gps_lat                 double precision,
    gps_lng                 double precision,
    gps_accuracy_meters     double precision,
    geofence_pass           boolean,
    qr_token_id             text,
    device_integrity_result text CHECK (device_integrity_result IN ('pass','fail','mock') OR device_integrity_result IS NULL),
    face_verified           boolean,
    mock_location_detected  boolean
);

CREATE INDEX IF NOT EXISTS idx_att_evidence_event ON public.attendance_evidence(event_id);

ALTER TABLE public.attendance_evidence ENABLE ROW LEVEL SECURITY;

-- Attendance Exceptions — flagged anomalies
CREATE TABLE IF NOT EXISTS public.attendance_exceptions (
    id              text PRIMARY KEY,
    event_id        text REFERENCES public.attendance_events(id) ON DELETE SET NULL,
    employee_id     text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    date            date NOT NULL,
    flag            text NOT NULL CHECK (flag IN (
        'missing_in','missing_out','out_of_geofence',
        'duplicate_scan','device_mismatch','overtime_without_approval'
    )),
    auto_generated  boolean NOT NULL DEFAULT true,
    resolved_at     timestamptz,
    resolved_by     text,
    notes           text,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_att_exceptions_employee ON public.attendance_exceptions(employee_id);
CREATE INDEX IF NOT EXISTS idx_att_exceptions_date ON public.attendance_exceptions(date);

ALTER TABLE public.attendance_exceptions ENABLE ROW LEVEL SECURITY;

-- Attendance Logs — computed daily summaries (can be recomputed)
CREATE TABLE IF NOT EXISTS public.attendance_logs (
    id              text PRIMARY KEY,
    employee_id     text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    date            date NOT NULL,
    check_in        text,
    check_out       text,
    hours           numeric,
    status          text NOT NULL DEFAULT 'absent'
                    CHECK (status IN ('present','absent','on_leave')),
    project_id      text,
    location_lat    double precision,
    location_lng    double precision,
    face_verified   boolean,
    late_minutes    integer,
    shift_id        text,
    flags           text[],
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (employee_id, date)
);

CREATE INDEX IF NOT EXISTS idx_att_logs_employee ON public.attendance_logs(employee_id);
CREATE INDEX IF NOT EXISTS idx_att_logs_date ON public.attendance_logs(date);

ALTER TABLE public.attendance_logs ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS set_attendance_logs_updated_at ON public.attendance_logs;
CREATE TRIGGER set_attendance_logs_updated_at
    BEFORE UPDATE ON public.attendance_logs
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Shift Templates
CREATE TABLE IF NOT EXISTS public.shift_templates (
    id              text PRIMARY KEY,
    name            text NOT NULL,
    start_time      text NOT NULL,
    end_time        text NOT NULL,
    grace_period    integer NOT NULL DEFAULT 10,
    break_duration  integer NOT NULL DEFAULT 60,
    work_days       integer[] NOT NULL DEFAULT '{1,2,3,4,5}',
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.shift_templates ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS set_shifts_updated_at ON public.shift_templates;
CREATE TRIGGER set_shifts_updated_at
    BEFORE UPDATE ON public.shift_templates
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Employee-to-Shift assignments
CREATE TABLE IF NOT EXISTS public.employee_shifts (
    employee_id text PRIMARY KEY REFERENCES public.employees(id) ON DELETE CASCADE,
    shift_id    text NOT NULL REFERENCES public.shift_templates(id) ON DELETE CASCADE,
    assigned_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.employee_shifts ENABLE ROW LEVEL SECURITY;

-- Holidays (PH holidays + custom)
CREATE TABLE IF NOT EXISTS public.holidays (
    id          text PRIMARY KEY,
    name        text NOT NULL,
    date        date NOT NULL,
    type        text NOT NULL CHECK (type IN ('regular','special')),
    multiplier  numeric NOT NULL DEFAULT 1.0,
    is_custom   boolean NOT NULL DEFAULT false,
    created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_holidays_date ON public.holidays(date);

ALTER TABLE public.holidays ENABLE ROW LEVEL SECURITY;

-- Overtime Requests
CREATE TABLE IF NOT EXISTS public.overtime_requests (
    id              text PRIMARY KEY,
    employee_id     text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    date            date NOT NULL,
    hours_requested numeric NOT NULL,
    reason          text NOT NULL,
    project_id      text,
    status          text NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('pending','approved','rejected')),
    requested_at    timestamptz NOT NULL DEFAULT now(),
    reviewed_by     text,
    reviewed_at     timestamptz,
    rejection_reason text
);

CREATE INDEX IF NOT EXISTS idx_ot_requests_employee ON public.overtime_requests(employee_id);
CREATE INDEX IF NOT EXISTS idx_ot_requests_status ON public.overtime_requests(status);

ALTER TABLE public.overtime_requests ENABLE ROW LEVEL SECURITY;

-- Anti-Cheat Penalty Records
CREATE TABLE IF NOT EXISTS public.penalty_records (
    id              text PRIMARY KEY,
    employee_id     text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    reason          text NOT NULL,
    triggered_at    timestamptz NOT NULL DEFAULT now(),
    penalty_until   timestamptz NOT NULL,
    resolved        boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_penalties_employee ON public.penalty_records(employee_id);

ALTER TABLE public.penalty_records ENABLE ROW LEVEL SECURITY;


-- ----------------------------------------------------------------------------
-- SOURCE: 022_kiosk_face_recognition_enhancement.sql
-- ----------------------------------------------------------------------------
-- Migration 022: Kiosk Face Recognition Enhancement
-- Adds face enrollment, project verification methods, dynamic QR tokens, and manual check-in

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ─────────────────────────────────────────────────────────────────────────────
-- Face Enrollment Tracking
-- Stores encrypted face templates for employee verification
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS face_enrollments (
  id TEXT PRIMARY KEY DEFAULT 'FE-' || gen_random_uuid()::text,
  employee_id TEXT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  face_template_hash TEXT NOT NULL,  -- Encrypted face template
  enrollment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_verified TIMESTAMPTZ,
  verification_count INTEGER DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  enrolled_by TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT face_enrollments_employee_unique UNIQUE (employee_id)
);

CREATE INDEX IF NOT EXISTS idx_face_enrollments_employee ON face_enrollments(employee_id);
CREATE INDEX IF NOT EXISTS idx_face_enrollments_active ON face_enrollments(is_active);

-- ─────────────────────────────────────────────────────────────────────────────
-- Project Verification Method Configuration
-- Admins select verification method per project
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS project_verification_methods (
  id TEXT PRIMARY KEY DEFAULT 'PVM-' || gen_random_uuid()::text,
  project_id TEXT NOT NULL,
  verification_method TEXT NOT NULL CHECK (verification_method IN (
    'face_only', 
    'qr_only', 
    'face_or_qr', 
    'manual_only'
  )),
  require_geofence BOOLEAN DEFAULT true,
  geofence_radius_meters INTEGER DEFAULT 100,
  allow_manual_override BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT project_verification_methods_project_unique UNIQUE(project_id)
);

CREATE INDEX IF NOT EXISTS idx_project_verification_methods_project ON project_verification_methods(project_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- Dynamic QR Tokens (replaces static QR)
-- Single-use, time-limited tokens for secure QR check-in
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS qr_tokens (
  id TEXT PRIMARY KEY DEFAULT 'QRT-' || gen_random_uuid()::text,
  device_id TEXT NOT NULL,
  employee_id TEXT REFERENCES employees(id) ON DELETE SET NULL,
  token TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  used BOOLEAN DEFAULT false,
  used_at TIMESTAMPTZ,
  used_by_kiosk_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add missing columns to qr_tokens if it already exists without them
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'qr_tokens' AND column_name = 'employee_id'
  ) THEN
    ALTER TABLE public.qr_tokens ADD COLUMN employee_id TEXT REFERENCES employees(id) ON DELETE SET NULL;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'qr_tokens' AND column_name = 'used_at'
  ) THEN
    ALTER TABLE public.qr_tokens ADD COLUMN used_at TIMESTAMPTZ;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'qr_tokens' AND column_name = 'used_by_kiosk_id'
  ) THEN
    ALTER TABLE public.qr_tokens ADD COLUMN used_by_kiosk_id TEXT;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_qr_tokens_token ON qr_tokens(token);
CREATE INDEX IF NOT EXISTS idx_qr_tokens_expires ON qr_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_qr_tokens_employee ON qr_tokens(employee_id);
CREATE INDEX IF NOT EXISTS idx_qr_tokens_used ON qr_tokens(used);

-- ─────────────────────────────────────────────────────────────────────────────
-- Manual Check-in Reasons
-- Predefined reasons for manual attendance logging
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS manual_checkin_reasons (
  id TEXT PRIMARY KEY DEFAULT 'MCR-' || gen_random_uuid()::text,
  reason TEXT NOT NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_manual_checkin_reasons_active ON manual_checkin_reasons(is_active);

-- Seed default manual check-in reasons
INSERT INTO manual_checkin_reasons (id, reason) VALUES
  ('MCR-001', 'Biometric system unavailable'),
  ('MCR-002', 'Employee forgot QR code'),
  ('MCR-003', 'Face recognition failed multiple attempts'),
  ('MCR-004', 'Visitor/Contractor check-in'),
  ('MCR-005', 'Emergency check-in'),
  ('MCR-006', 'System maintenance'),
  ('MCR-007', 'Other')
ON CONFLICT DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────
-- Manual Check-in Log
-- Audit trail for manual attendance entries
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS manual_checkins (
  id TEXT PRIMARY KEY DEFAULT 'MCI-' || gen_random_uuid()::text,
  employee_id TEXT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN ('IN', 'OUT')),
  reason_id TEXT REFERENCES manual_checkin_reasons(id),
  custom_reason TEXT,
  performed_by TEXT NOT NULL REFERENCES employees(id),
  timestamp_utc TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  project_id TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_manual_checkins_employee ON manual_checkins(employee_id);
CREATE INDEX IF NOT EXISTS idx_manual_checkins_timestamp ON manual_checkins(timestamp_utc);
CREATE INDEX IF NOT EXISTS idx_manual_checkins_performed_by ON manual_checkins(performed_by);

-- ─────────────────────────────────────────────────────────────────────────────
-- Kiosk Access PINs
-- Secure PIN-based access for kiosk terminals
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS kiosk_pins (
  id TEXT PRIMARY KEY DEFAULT 'KP-' || gen_random_uuid()::text,
  kiosk_device_id TEXT,
  pin_hash TEXT NOT NULL,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_used_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT true,
  CONSTRAINT kiosk_pins_device_unique UNIQUE (kiosk_device_id)
);

CREATE INDEX IF NOT EXISTS idx_kiosk_pins_device ON kiosk_pins(kiosk_device_id);
CREATE INDEX IF NOT EXISTS idx_kiosk_pins_active ON kiosk_pins(is_active);

-- ─────────────────────────────────────────────────────────────────────────────
-- Add verification_method column to projects table (denormalized for performance)
-- ─────────────────────────────────────────────────────────────────────────────

-- NOTE: verification_method, require_geofence, geofence_radius_meters are now
-- declared directly on the projects CREATE TABLE in 08_tasks_projects_messaging.sql.
-- This DO block is kept for backwards compatibility when running independently.
DO $$ 
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='projects') THEN
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.columns 
      WHERE table_schema = 'public' 
      AND table_name = 'projects' 
      AND column_name = 'verification_method'
    ) THEN
      ALTER TABLE public.projects 
        ADD COLUMN verification_method TEXT CHECK (verification_method IN (
          'face_only', 'qr_only', 'face_or_qr', 'manual_only'
        )) DEFAULT 'face_or_qr',
        ADD COLUMN require_geofence BOOLEAN DEFAULT true,
        ADD COLUMN geofence_radius_meters INTEGER DEFAULT 100;
    END IF;
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- Helper: is_admin() — not defined in earlier migrations, define it here
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN public.get_user_role() = 'admin';
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Helper: check if current user is the given employee (used by RLS policies)
CREATE OR REPLACE FUNCTION public.is_own_employee(emp_id text)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.employees
    WHERE id = emp_id AND profile_id = auth.uid()
  );
$$;

-- ─────────────────────────────────────────────────────────────────────────────
-- Auto-update triggers for updated_at columns
-- ─────────────────────────────────────────────────────────────────────────────

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply triggers to new tables
DROP TRIGGER IF EXISTS update_face_enrollments_updated_at ON public.face_enrollments;
CREATE TRIGGER update_face_enrollments_updated_at
  BEFORE UPDATE ON public.face_enrollments
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

DROP TRIGGER IF EXISTS update_project_verification_methods_updated_at ON public.project_verification_methods;
CREATE TRIGGER update_project_verification_methods_updated_at
  BEFORE UPDATE ON public.project_verification_methods
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ─────────────────────────────────────────────────────────────────────────────
-- Row Level Security (RLS) Policies
-- ─────────────────────────────────────────────────────────────────────────────

-- Enable RLS on all new tables
ALTER TABLE public.face_enrollments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_verification_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qr_tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.manual_checkins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kiosk_pins ENABLE ROW LEVEL SECURITY;

-- Face enrollments: employees can view own, admin/HR can view all
DROP POLICY IF EXISTS fe_select_own ON public.face_enrollments;
CREATE POLICY fe_select_own ON public.face_enrollments
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM employees e 
      WHERE e.id = face_enrollments.employee_id 
      AND e.profile_id = auth.uid()
    )
    OR public.is_admin_or_hr()
  );

DROP POLICY IF EXISTS fe_insert ON public.face_enrollments;
CREATE POLICY fe_insert ON public.face_enrollments
  FOR INSERT WITH CHECK (public.is_admin_or_hr());

DROP POLICY IF EXISTS fe_update ON public.face_enrollments;
CREATE POLICY fe_update ON public.face_enrollments
  FOR UPDATE USING (public.is_admin_or_hr());

-- Project verification methods: read for all, write for admin
DROP POLICY IF EXISTS pvm_select ON public.project_verification_methods;
CREATE POLICY pvm_select ON public.project_verification_methods
  FOR SELECT USING (true);

DROP POLICY IF EXISTS pvm_insert ON public.project_verification_methods;
CREATE POLICY pvm_insert ON public.project_verification_methods
  FOR INSERT WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS pvm_update ON public.project_verification_methods;
CREATE POLICY pvm_update ON public.project_verification_methods
  FOR UPDATE USING (public.is_admin());

DROP POLICY IF EXISTS pvm_delete ON public.project_verification_methods;
CREATE POLICY pvm_delete ON public.project_verification_methods
  FOR DELETE USING (public.is_admin());

-- QR tokens: service role only (generated by kiosk backend)
-- No RLS policies - accessed via service role only for security

-- Manual check-ins: employees view own, admin/HR view all
DROP POLICY IF EXISTS mci_select ON public.manual_checkins;
CREATE POLICY mci_select ON public.manual_checkins
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM employees e 
      WHERE e.id = manual_checkins.employee_id 
      AND e.profile_id = auth.uid()
    )
    OR public.is_admin_or_hr()
  );

DROP POLICY IF EXISTS mci_insert ON public.manual_checkins;
CREATE POLICY mci_insert ON public.manual_checkins
  FOR INSERT WITH CHECK (public.is_admin_or_hr());

-- Kiosk PINs: admin only
DROP POLICY IF EXISTS kp_select ON public.kiosk_pins;
CREATE POLICY kp_select ON public.kiosk_pins
  FOR SELECT USING (public.is_admin());

DROP POLICY IF EXISTS kp_insert ON public.kiosk_pins;
CREATE POLICY kp_insert ON public.kiosk_pins
  FOR INSERT WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS kp_update ON public.kiosk_pins;
CREATE POLICY kp_update ON public.kiosk_pins
  FOR UPDATE USING (public.is_admin());

-- ─────────────────────────────────────────────────────────────────────────────
-- Helper Functions
-- ─────────────────────────────────────────────────────────────────────────────

-- Function to check if employee has enrolled face
CREATE OR REPLACE FUNCTION public.has_enrolled_face(emp_id TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM face_enrollments 
    WHERE employee_id = emp_id 
    AND is_active = true
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to get project verification method
CREATE OR REPLACE FUNCTION public.get_project_verification_method(proj_id TEXT)
RETURNS TEXT AS $$
DECLARE
  method TEXT;
BEGIN
  -- First check project_verification_methods table
  SELECT verification_method INTO method
  FROM project_verification_methods
  WHERE project_id = proj_id;
  
  -- If not found, check denormalized column in projects table
  IF method IS NULL THEN
    SELECT verification_method INTO method
    FROM projects
    WHERE id = proj_id;
  END IF;
  
  RETURN COALESCE(method, 'face_or_qr');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function to validate QR token
CREATE OR REPLACE FUNCTION public.validate_qr_token(token_value TEXT, kiosk_id TEXT)
RETURNS TABLE (valid BOOLEAN, employee_id TEXT, message TEXT) AS $$
DECLARE
  token_record RECORD;
BEGIN
  -- Get token record
  SELECT * INTO token_record
  FROM qr_tokens
  WHERE qr_tokens.token = token_value;
  
  -- Check if token exists
  IF token_record IS NULL THEN
    RETURN QUERY SELECT false, NULL::TEXT, 'Invalid token'::TEXT;
    RETURN;
  END IF;
  
  -- Check if token is already used
  IF token_record.used THEN
    RETURN QUERY SELECT false, NULL::TEXT, 'Token already used'::TEXT;
    RETURN;
  END IF;
  
  -- Check if token is expired
  IF token_record.expires_at < NOW() THEN
    RETURN QUERY SELECT false, NULL::TEXT, 'Token expired'::TEXT;
    RETURN;
  END IF;
  
  -- Check if device matches (if provided)
  IF kiosk_id IS NOT NULL AND token_record.device_id != kiosk_id THEN
    RETURN QUERY SELECT false, NULL::TEXT, 'Invalid device'::TEXT;
    RETURN;
  END IF;
  
  -- Token is valid - mark as used
  UPDATE qr_tokens
  SET used = true, used_at = NOW(), used_by_kiosk_id = kiosk_id
  WHERE id = token_record.id;
  
  RETURN QUERY SELECT true, token_record.employee_id, 'Valid token'::TEXT;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Comment describing the migration
COMMENT ON SCHEMA public IS 'Migration 022: Added face enrollment, project verification methods, dynamic QR tokens, manual check-in, and kiosk PINs';


-- ----------------------------------------------------------------------------
-- SOURCE: 023_face_embedding_support.sql
-- ----------------------------------------------------------------------------
-- Migration 023: Face Embedding Support
-- Adds real 128-dimensional face embeddings for biometric matching
-- Replaces text-based face_template_hash with proper numeric embeddings

-- ─────────────────────────────────────────────────────────────────────────────
-- Add embedding column to face_enrollments
-- Stores the 128-dimensional face descriptor from face-api.js
-- ─────────────────────────────────────────────────────────────────────────────

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
    AND table_name = 'face_enrollments'
    AND column_name = 'embedding'
  ) THEN
    ALTER TABLE public.face_enrollments
    ADD COLUMN embedding JSONB;

    COMMENT ON COLUMN public.face_enrollments.embedding
    IS 'Array of 128 float64 values representing the face descriptor from face-api.js';
  END IF;
END $$;

-- ─────────────────────────────────────────────────────────────────────────────
-- Euclidean distance function for face matching
-- Compares a query embedding against all enrolled embeddings
-- Returns the closest match if within threshold
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.match_face_embedding(
  query_embedding JSONB,
  match_threshold FLOAT8 DEFAULT 0.75
)
RETURNS TABLE(
  employee_id TEXT,
  distance FLOAT8,
  enrollment_id TEXT
) AS $$
DECLARE
  q_arr FLOAT8[];
BEGIN
  -- Convert JSONB array to native float8 array
  SELECT array_agg(val::FLOAT8)
  INTO q_arr
  FROM jsonb_array_elements_text(query_embedding) AS val;

  -- Use a CTE to compute distance per row first, then filter with WHERE
  -- (HAVING without GROUP BY cannot filter individual rows in PostgreSQL)
  RETURN QUERY
  WITH computed AS (
    SELECT
      fe.employee_id,
      fe.id AS enrollment_id,
      sqrt(
        (SELECT sum(power(q.val - e.val, 2))
         FROM unnest(q_arr) WITH ORDINALITY AS q(val, idx),
              unnest(
                (SELECT array_agg(v::FLOAT8)
                 FROM jsonb_array_elements_text(fe.embedding) AS v)
              ) WITH ORDINALITY AS e(val, idx)
         WHERE q.idx = e.idx)
      ) AS dist
    FROM face_enrollments fe
    WHERE fe.is_active = true
      AND fe.embedding IS NOT NULL
      AND jsonb_array_length(fe.embedding) = 128
  )
  SELECT c.employee_id, c.dist AS distance, c.enrollment_id
  FROM computed c
  WHERE c.dist < match_threshold
  ORDER BY c.dist
  LIMIT 1;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ─────────────────────────────────────────────────────────────────────────────
-- Verify face embedding against a specific employee
-- Returns the distance between query and employee's stored embedding
-- ─────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.verify_face_embedding(
  p_employee_id TEXT,
  query_embedding JSONB,
  match_threshold FLOAT8 DEFAULT 0.75
)
RETURNS TABLE(
  matched BOOLEAN,
  distance FLOAT8
) AS $$
DECLARE
  stored_embedding JSONB;
  q_arr FLOAT8[];
  s_arr FLOAT8[];
  dist FLOAT8;
BEGIN
  -- Get stored embedding
  SELECT fe.embedding INTO stored_embedding
  FROM face_enrollments fe
  WHERE fe.employee_id = p_employee_id
    AND fe.is_active = true
    AND fe.embedding IS NOT NULL;

  IF stored_embedding IS NULL THEN
    RETURN QUERY SELECT false, 999.0::FLOAT8;
    RETURN;
  END IF;

  -- Convert to arrays
  SELECT array_agg(val::FLOAT8) INTO q_arr
  FROM jsonb_array_elements_text(query_embedding) AS val;

  SELECT array_agg(val::FLOAT8) INTO s_arr
  FROM jsonb_array_elements_text(stored_embedding) AS val;

  -- Compute euclidean distance
  SELECT sqrt(sum(power(q.val - s.val, 2))) INTO dist
  FROM unnest(q_arr) WITH ORDINALITY AS q(val, idx),
       unnest(s_arr) WITH ORDINALITY AS s(val, idx)
  WHERE q.idx = s.idx;

  -- Update verification stats
  IF dist < match_threshold THEN
    UPDATE face_enrollments
    SET last_verified = NOW(),
        verification_count = verification_count + 1
    WHERE employee_id = p_employee_id AND is_active = true;
  END IF;

  RETURN QUERY SELECT (dist < match_threshold), dist;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- ----------------------------------------------------------------------------
-- SOURCE: 025_employee_attendance_log_write.sql
-- ----------------------------------------------------------------------------
-- Migration 025: Allow employees to upsert their own attendance logs
-- ─────────────────────────────────────────────────────────────────────────────
-- Context: The write-through sync layer (sync.service.ts) now lets employees
-- upsert their own attendance_logs rows on check-in/check-out.  Without an
-- INSERT policy the upsert silently fails and the log is lost on hard refresh.
--
-- Policies added:
--   al_insert_own  — employees can INSERT a log for themselves
--   al_update_own  — employees can UPDATE a log that belongs to themselves
-- ─────────────────────────────────────────────────────────────────────────────

-- Insert: employee may create a log where employee_id resolves to their own record
DROP POLICY IF EXISTS al_insert_own ON public.attendance_logs;
CREATE POLICY al_insert_own ON public.attendance_logs
    FOR INSERT WITH CHECK (public.is_own_employee(employee_id));

-- Update: employee may update a log that already belongs to them
DROP POLICY IF EXISTS al_update_own ON public.attendance_logs;
CREATE POLICY al_update_own ON public.attendance_logs
    FOR UPDATE USING (public.is_own_employee(employee_id))
    WITH CHECK (public.is_own_employee(employee_id));


-- ----------------------------------------------------------------------------
-- SOURCE: 026_face_reference_images.sql
-- ----------------------------------------------------------------------------
-- Migration: Add reference_image column to face_enrollments
-- Stores a base64 JPEG of the enrollment face crop for AI-powered face comparison.
-- This enables server-side Qwen VL face matching (much more accurate than embedding-only).

ALTER TABLE public.face_enrollments
ADD COLUMN IF NOT EXISTS reference_image TEXT;

COMMENT ON COLUMN public.face_enrollments.reference_image IS
  'Base64 JPEG of the best enrollment face crop for AI face comparison';


-- ----------------------------------------------------------------------------
-- SOURCE: 033_fix_location_pings_rls.sql
-- NOTE: location_pings, site_survey_photos, and break_records are created in
-- 08_tasks_projects_messaging.sql (runs after this file). These RLS policies
-- are applied in 15_rls_policies.sql which runs after migration 08.
-- Skipping here to avoid forward-reference errors on fresh install.
-- ----------------------------------------------------------------------------


-- ----------------------------------------------------------------------------
-- SOURCE: 041_face_recognition_test_account.sql
-- ----------------------------------------------------------------------------
-- Migration 041: Face Recognition Test Account
-- Creates a dedicated employee + project for testing biometric face check-in.
-- This account is pre-configured for face_only verification and visible
-- in the demo login page as "Face Demo" (face@sdsi.com / demo1234).

-- ─── 1. Insert employee record ────────────────────────────────────────────────
INSERT INTO public.employees (
    id, name, email, role, department, status, work_type,
    salary, join_date, productivity, location, phone, birthday,
    work_days, pay_frequency, whatsapp_number, preferred_channel,
    address, emergency_contact, pin, nfc_id, created_at, updated_at
)
VALUES (
    'EMP029',
    'Alex Reyes',
    'face@sdsi.com',
    'employee',
    'Operations',
    'active',
    'ONSITE',
    52000,
    '2025-01-15',
    90,
    'Makati, Metro Manila',
    '+63-917-5550029',
    '1993-07-14',
    ARRAY['Mon','Tue','Wed','Thu','Fri'],
    'semi_monthly',
    '+63-917-5550029',
    'in_app',
    '29 Dela Rosa Street, Legazpi Village, Makati City, Metro Manila',
    'Rosa Reyes (Mother) - +63-918-5550029',
    '290290',
    'NFC-029',
    NOW(),
    NOW()
)
ON CONFLICT (id) DO UPDATE SET
    name            = EXCLUDED.name,
    email           = EXCLUDED.email,
    status          = EXCLUDED.status,
    department      = EXCLUDED.department,
    work_type       = EXCLUDED.work_type,
    updated_at      = NOW();

-- ─── 2 + 3. Seed: PRJ006 + assignment — moved to 08_tasks_projects_messaging.sql
-- (projects and project_assignments tables are defined in migration 08)

-- ─── 4. Enable Realtime for face_enrollments if not already enabled ───────────
-- (idempotent — safe to run multiple times)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_publication_tables
        WHERE pubname = 'supabase_realtime'
          AND schemaname = 'public'
          AND tablename = 'face_enrollments'
    ) THEN
        ALTER PUBLICATION supabase_realtime ADD TABLE public.face_enrollments;
    END IF;
END
$$;


-- ----------------------------------------------------------------------------
-- SOURCE: 051_kiosk_config.sql
-- ----------------------------------------------------------------------------
-- ─── Kiosk configuration singleton table ───────────────────────────────────
-- Stores all kiosk UI/behavior settings (one row with id = 'default')

CREATE TABLE IF NOT EXISTS public.kiosk_config (
  id text NOT NULL DEFAULT 'default'::text,

  -- General
  kiosk_enabled boolean NOT NULL DEFAULT true,
  kiosk_title text NOT NULL DEFAULT 'Attendance Kiosk'::text,
  welcome_message text NOT NULL DEFAULT 'Choose a method to check in or out'::text,
  footer_message text NOT NULL DEFAULT 'Unauthorized access is prohibited'::text,

  -- Check-in methods
  check_in_method text NOT NULL DEFAULT 'all'::text,
  enable_pin boolean NOT NULL DEFAULT true,
  enable_qr boolean NOT NULL DEFAULT true,
  enable_face boolean NOT NULL DEFAULT true,
  enable_nfc boolean NOT NULL DEFAULT true,
  allow_check_out boolean NOT NULL DEFAULT true,

  -- PIN settings
  pin_length integer NOT NULL DEFAULT 6,
  max_pin_attempts integer NOT NULL DEFAULT 0,
  lockout_duration integer NOT NULL DEFAULT 60,

  -- QR / Token
  token_refresh_interval integer NOT NULL DEFAULT 30,
  token_length integer NOT NULL DEFAULT 8,

  -- NFC
  nfc_simulated_delay integer NOT NULL DEFAULT 1500,

  -- Display
  kiosk_theme text NOT NULL DEFAULT 'auto'::text,
  clock_format text NOT NULL DEFAULT '24h'::text,
  show_clock boolean NOT NULL DEFAULT true,
  show_date boolean NOT NULL DEFAULT true,
  show_logo boolean NOT NULL DEFAULT true,
  show_device_id boolean NOT NULL DEFAULT true,
  show_security_badge boolean NOT NULL DEFAULT true,

  -- Behavior
  feedback_duration integer NOT NULL DEFAULT 1800,
  warn_off_day boolean NOT NULL DEFAULT true,
  play_sound boolean NOT NULL DEFAULT false,
  idle_timeout integer NOT NULL DEFAULT 0,
  idle_action text NOT NULL DEFAULT 'none'::text,

  -- Security
  require_geofence boolean NOT NULL DEFAULT false,

  -- Selfie
  selfie_enabled boolean NOT NULL DEFAULT false,
  selfie_required boolean NOT NULL DEFAULT false,

  -- Face Recognition
  face_rec_enabled boolean NOT NULL DEFAULT true,
  face_rec_required boolean NOT NULL DEFAULT false,
  face_rec_auto_start boolean NOT NULL DEFAULT true,
  face_rec_countdown integer NOT NULL DEFAULT 3,
  face_rec_position text NOT NULL DEFAULT 'bottom'::text,

  -- Anti-Cheat
  dev_options_penalty_enabled boolean NOT NULL DEFAULT true,
  dev_options_penalty_minutes integer NOT NULL DEFAULT 30,
  dev_options_penalty_apply_to text NOT NULL DEFAULT 'both'::text,
  dev_options_penalty_notify_admin boolean NOT NULL DEFAULT true,

  updated_at timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT kiosk_config_pkey PRIMARY KEY (id)
);

-- Seed default row
INSERT INTO public.kiosk_config (id) VALUES ('default') ON CONFLICT DO NOTHING;

-- RLS
ALTER TABLE public.kiosk_config ENABLE ROW LEVEL SECURITY;

-- Anyone authenticated can read (kiosk pages need these settings)
CREATE POLICY "Authenticated users can read kiosk config"
  ON public.kiosk_config FOR SELECT
  TO authenticated
  USING (true);

-- Only admins can update (enforced at API level too, but defense in depth)
CREATE POLICY "Admins can update kiosk config"
  ON public.kiosk_config FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Admins can insert kiosk config"
  ON public.kiosk_config FOR INSERT
  TO authenticated
  WITH CHECK (true);

