-- ============================================================================
-- 06_payroll.sql
-- ----------------------------------------------------------------------------
-- Consolidated from legacy migrations: 006, 016, 024, 028, 036, 037, 038, 039, 045, 048, 054
-- Apply order: run this file in the same numeric order as the file name.
-- Generated by scripts/build-migrations-v2.ps1 â€” DO NOT EDIT BY HAND.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SOURCE: 006_payroll.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 006_payroll.sql
-- Payslips, payroll runs, adjustments, final pay, pay schedule
-- ============================================================

-- Pay Schedule Config (singleton-ish — one active row)
CREATE TABLE IF NOT EXISTS public.pay_schedule_config (
    id                          text PRIMARY KEY DEFAULT 'default',
    default_frequency           text NOT NULL DEFAULT 'semi_monthly'
                                CHECK (default_frequency IN ('monthly','semi_monthly','bi_weekly','weekly')),
    semi_monthly_first_cutoff   integer NOT NULL DEFAULT 15,
    semi_monthly_first_pay_day  integer NOT NULL DEFAULT 20,
    semi_monthly_second_pay_day integer NOT NULL DEFAULT 5,
    monthly_pay_day             integer NOT NULL DEFAULT 30,
    bi_weekly_start_date        date,
    weekly_pay_day              integer NOT NULL DEFAULT 5,
    deduct_gov_from             text NOT NULL DEFAULT 'second'
                                CHECK (deduct_gov_from IN ('first','second','both')),
    updated_at                  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.pay_schedule_config ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS set_pay_schedule_config_updated_at ON public.pay_schedule_config;
CREATE TRIGGER set_pay_schedule_config_updated_at
    BEFORE UPDATE ON public.pay_schedule_config
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Payroll Runs
CREATE TABLE IF NOT EXISTS public.payroll_runs (
    id                text PRIMARY KEY,
    period_label      text NOT NULL,
    created_at        timestamptz NOT NULL DEFAULT now(),
    status            text NOT NULL DEFAULT 'draft'
                      CHECK (status IN ('draft','validated','locked','published','paid')),
    locked            boolean NOT NULL DEFAULT false,
    locked_at         timestamptz,
    published_at      timestamptz,
    paid_at           timestamptz,
    payslip_ids       text[] NOT NULL DEFAULT '{}',
    policy_snapshot   jsonb,
    run_type          text DEFAULT 'regular'
                      CHECK (run_type IN ('regular','adjustment','13th_month','final_pay'))
);

CREATE INDEX IF NOT EXISTS idx_payroll_runs_status ON public.payroll_runs(status);

ALTER TABLE public.payroll_runs ENABLE ROW LEVEL SECURITY;

-- Payslips
CREATE TABLE IF NOT EXISTS public.payslips (
    id                      text PRIMARY KEY,
    employee_id             text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    period_start            date NOT NULL,
    period_end              date NOT NULL,
    pay_frequency           text CHECK (pay_frequency IN ('monthly','semi_monthly','bi_weekly','weekly')),
    gross_pay               numeric NOT NULL DEFAULT 0,
    allowances              numeric NOT NULL DEFAULT 0,
    sss_deduction           numeric NOT NULL DEFAULT 0,
    philhealth_deduction    numeric NOT NULL DEFAULT 0,
    pagibig_deduction       numeric NOT NULL DEFAULT 0,
    tax_deduction           numeric NOT NULL DEFAULT 0,
    other_deductions        numeric NOT NULL DEFAULT 0,
    loan_deduction          numeric NOT NULL DEFAULT 0,
    holiday_pay             numeric DEFAULT 0,
    net_pay                 numeric NOT NULL DEFAULT 0,
    issued_at               date NOT NULL,
    status                  text NOT NULL DEFAULT 'issued'
                            CHECK (status IN ('issued','confirmed','published','paid','acknowledged')),
    confirmed_at            timestamptz,
    published_at            timestamptz,
    paid_at                 timestamptz,
    payment_method          text,
    bank_reference_id       text,
    payroll_batch_id        text,
    pdf_hash                text,
    notes                   text,
    signed_at               timestamptz,
    signature_data_url      text,
    ack_text_version        text,
    adjustment_ref          text,
    acknowledged_at         timestamptz,
    acknowledged_by         text,
    paid_confirmed_by       text,
    paid_confirmed_at       timestamptz
);

CREATE INDEX IF NOT EXISTS idx_payslips_employee ON public.payslips(employee_id);
CREATE INDEX IF NOT EXISTS idx_payslips_status ON public.payslips(status);
CREATE INDEX IF NOT EXISTS idx_payslips_period ON public.payslips(period_start, period_end);

ALTER TABLE public.payslips ENABLE ROW LEVEL SECURITY;

-- Payroll Adjustments
CREATE TABLE IF NOT EXISTS public.payroll_adjustments (
    id                  text PRIMARY KEY,
    payroll_run_id      text NOT NULL,
    employee_id         text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    adjustment_type     text NOT NULL CHECK (adjustment_type IN ('earnings','deduction','net_correction','statutory_correction')),
    reference_payslip_id text NOT NULL,
    amount              numeric NOT NULL,
    reason              text NOT NULL,
    created_by          text NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    approved_by         text,
    approved_at         timestamptz,
    applied_run_id      text,
    status              text NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending','approved','applied','rejected'))
);

CREATE INDEX IF NOT EXISTS idx_adj_employee ON public.payroll_adjustments(employee_id);
CREATE INDEX IF NOT EXISTS idx_adj_run ON public.payroll_adjustments(payroll_run_id);

ALTER TABLE public.payroll_adjustments ENABLE ROW LEVEL SECURITY;

-- Final Pay Computations
CREATE TABLE IF NOT EXISTS public.final_pay_computations (
    id                      text PRIMARY KEY,
    employee_id             text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    resigned_at             date NOT NULL,
    pro_rated_salary        numeric NOT NULL DEFAULT 0,
    unpaid_ot               numeric NOT NULL DEFAULT 0,
    leave_payout            numeric NOT NULL DEFAULT 0,
    remaining_loan_balance  numeric NOT NULL DEFAULT 0,
    gross_final_pay         numeric NOT NULL DEFAULT 0,
    deductions              numeric NOT NULL DEFAULT 0,
    net_final_pay           numeric NOT NULL DEFAULT 0,
    status                  text NOT NULL DEFAULT 'draft'
                            CHECK (status IN ('draft','validated','locked','published','paid')),
    created_at              timestamptz NOT NULL DEFAULT now(),
    payslip_id              text
);

CREATE INDEX IF NOT EXISTS idx_final_pay_employee ON public.final_pay_computations(employee_id);

ALTER TABLE public.final_pay_computations ENABLE ROW LEVEL SECURITY;


-- ----------------------------------------------------------------------------
-- SOURCE: 016_fix_loans_timestamp.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 016_fix_loans_timestamp.sql
-- Fix loans.created_at: date → timestamptz (align with all other tables)
-- ============================================================

DO $$
BEGIN
    -- Only ALTER if the column type is 'date' (not already timestamptz)
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name   = 'loans'
          AND column_name  = 'created_at'
          AND data_type    = 'date'
    ) THEN
        ALTER TABLE public.loans
            ALTER COLUMN created_at TYPE timestamptz USING created_at::timestamptz,
            ALTER COLUMN created_at SET DEFAULT now();
    END IF;
END $$;


-- ----------------------------------------------------------------------------
-- SOURCE: 024_finance_rls_fixes.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 024_finance_rls_fixes.sql
-- Grant finance and payroll_admin appropriate read/write access:
--   • employees  : read all + manage (salary edits, payroll processing)
--   • leave_balances  : read-only (payroll deduction calculations)
--   • attendance_logs : read-only (payroll hours calculations)
-- Fix channel_messages UPDATE for employees (read-receipt / own-message edits)
-- The write-through layer in sync.service.ts is separately gated
-- to prevent finance from writing leave_balances/attendance_logs.
-- ============================================================

-- ─── Employees: expand read to finance / payroll_admin / auditor ──────────
DROP POLICY IF EXISTS employees_read_admin ON public.employees;
CREATE POLICY employees_read_admin ON public.employees
    FOR SELECT USING (
        public.get_user_role() IN ('admin', 'hr', 'finance', 'payroll_admin', 'auditor')
    );

-- Employees: expand manage (INSERT/UPDATE/DELETE) to finance / payroll_admin
-- Finance legitimately edits salary fields and the finance-view already allows it.
DROP POLICY IF EXISTS employees_manage_admin ON public.employees;
CREATE POLICY employees_manage_admin ON public.employees
    FOR ALL USING (
        public.get_user_role() IN ('admin', 'hr', 'finance', 'payroll_admin')
    );

-- ─── Leave balances: finance / payroll_admin can read (deduction calc) ────
-- Leave them out of lb_manage so they cannot create or modify balances.
DROP POLICY IF EXISTS lb_read_admin ON public.leave_balances;
CREATE POLICY lb_read_admin ON public.leave_balances
    FOR SELECT USING (
        public.get_user_role() IN ('admin', 'hr', 'finance', 'payroll_admin', 'auditor')
    );

-- ─── Attendance logs: finance / payroll_admin can read (hours calc) ───────
-- Leave them out of al_manage so they cannot create or modify logs.
DROP POLICY IF EXISTS al_read_admin ON public.attendance_logs;
CREATE POLICY al_read_admin ON public.attendance_logs
    FOR SELECT USING (
        public.get_user_role() IN ('admin', 'hr', 'finance', 'payroll_admin', 'auditor')
    );

-- ─── Channel messages: allow employees to update their own messages ────────
-- NOTE: channel_messages is created in 08_tasks_projects_messaging.sql.
-- These policies have been moved to 15_rls_policies.sql to avoid forward references.

-- ─── Face enrollments: allow employees to self-enroll ─────────────────────
-- Existing policies fe_insert/fe_update are admin-only; add employee self-service.
-- Employees can only insert/update their OWN enrollment row.
DROP POLICY IF EXISTS fe_self_insert ON public.face_enrollments;
CREATE POLICY fe_self_insert ON public.face_enrollments
    FOR INSERT WITH CHECK (
        public.is_own_employee(employee_id) OR public.is_admin_or_hr()
    );

DROP POLICY IF EXISTS fe_self_update ON public.face_enrollments;
CREATE POLICY fe_self_update ON public.face_enrollments
    FOR UPDATE USING (
        public.is_own_employee(employee_id) OR public.is_admin_or_hr()
    )
    WITH CHECK (
        public.is_own_employee(employee_id) OR public.is_admin_or_hr()
    );

-- Drop the old admin-only policies so they don't conflict
DROP POLICY IF EXISTS fe_insert ON public.face_enrollments;
DROP POLICY IF EXISTS fe_update ON public.face_enrollments;


-- ----------------------------------------------------------------------------
-- SOURCE: 028_payroll_run_payslips_junction.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 028_payroll_run_payslips_junction.sql
-- Replace payroll_runs.payslip_ids text[] with proper junction table.
-- Maintains backward compatibility during transition.
-- ============================================================

-- ─── Junction table ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.payroll_run_payslips (
    run_id      text NOT NULL REFERENCES public.payroll_runs(id) ON DELETE CASCADE,
    payslip_id  text NOT NULL REFERENCES public.payslips(id) ON DELETE CASCADE,
    added_at    timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, payslip_id)
);

CREATE INDEX IF NOT EXISTS idx_prp_payslip ON public.payroll_run_payslips(payslip_id);

ALTER TABLE public.payroll_run_payslips ENABLE ROW LEVEL SECURITY;

-- RLS: match parent table (payroll_runs) access pattern
CREATE POLICY "payroll_run_payslips_read"
    ON public.payroll_run_payslips
    FOR SELECT
    TO authenticated
    USING (
        public.get_user_role() IN ('admin', 'finance', 'payroll_admin', 'auditor')
    );

CREATE POLICY "payroll_run_payslips_write"
    ON public.payroll_run_payslips
    FOR ALL
    TO authenticated
    USING (
        public.get_user_role() IN ('admin', 'finance', 'payroll_admin')
    )
    WITH CHECK (
        public.get_user_role() IN ('admin', 'finance', 'payroll_admin')
    );

-- ─── Migrate existing data ───────────────────────────────────
-- Move payslip_ids array entries into the junction table.

INSERT INTO public.payroll_run_payslips (run_id, payslip_id)
SELECT pr.id, unnest(pr.payslip_ids)
FROM public.payroll_runs pr
WHERE array_length(pr.payslip_ids, 1) > 0
ON CONFLICT DO NOTHING;

-- ─── Keep the old column but mark it deprecated ──────────────
-- The column will be dropped in a future migration after all code
-- has been migrated to use the junction table.
COMMENT ON COLUMN public.payroll_runs.payslip_ids
    IS 'DEPRECATED — use payroll_run_payslips junction table. Will be removed in a future migration.';


-- ----------------------------------------------------------------------------
-- SOURCE: 036_deduction_overrides.sql
-- ----------------------------------------------------------------------------
-- ═══════════════════════════════════════════════════════════════
-- Migration 036: Government Deduction Overrides (Philippine Standard)
-- 
-- Stores per-employee override settings for SSS, PhilHealth,
-- Pag-IBIG, and BIR withholding tax. Supports: auto (standard PH
-- calculation), exempt (₱0), percentage (% of gross), or fixed (₱).
-- ═══════════════════════════════════════════════════════════════

-- Per-employee, per-deduction-type overrides
CREATE TABLE IF NOT EXISTS public.deduction_overrides (
    id text NOT NULL DEFAULT ('DO-' || gen_random_uuid()::text),
    employee_id text NOT NULL,
    deduction_type text NOT NULL CHECK (deduction_type IN ('sss', 'philhealth', 'pagibig', 'bir')),
    mode text NOT NULL DEFAULT 'auto' CHECK (mode IN ('auto', 'exempt', 'percentage', 'fixed')),
    percentage numeric CHECK (percentage >= 0 AND percentage <= 100),
    fixed_amount numeric CHECK (fixed_amount >= 0),
    notes text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text,
    CONSTRAINT deduction_overrides_pkey PRIMARY KEY (id),
    CONSTRAINT deduction_overrides_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE,
    CONSTRAINT deduction_overrides_unique UNIQUE (employee_id, deduction_type)
);

-- Global default overrides (company-wide; employee_id = 'global')
-- e.g., "All employees SSS at 4.5%" — per-employee overrides take precedence
CREATE TABLE IF NOT EXISTS public.deduction_global_defaults (
    id text NOT NULL DEFAULT ('DGD-' || gen_random_uuid()::text),
    deduction_type text NOT NULL CHECK (deduction_type IN ('sss', 'philhealth', 'pagibig', 'bir')),
    enabled boolean NOT NULL DEFAULT true,
    mode text NOT NULL DEFAULT 'auto' CHECK (mode IN ('auto', 'exempt', 'percentage', 'fixed')),
    percentage numeric CHECK (percentage >= 0 AND percentage <= 100),
    fixed_amount numeric CHECK (fixed_amount >= 0),
    notes text,
    updated_at timestamptz NOT NULL DEFAULT now(),
    updated_by text,
    CONSTRAINT deduction_global_defaults_pkey PRIMARY KEY (id),
    CONSTRAINT deduction_global_defaults_unique UNIQUE (deduction_type)
);

-- Seed global defaults (all auto by default)
INSERT INTO public.deduction_global_defaults (id, deduction_type, enabled, mode, notes)
VALUES
    ('DGD-SSS',   'sss',        true, 'auto', 'SSS 2026 table — RA 11199'),
    ('DGD-PH',    'philhealth', true, 'auto', 'PhilHealth 5% — RA 11223 UHC Act'),
    ('DGD-PI',    'pagibig',    true, 'auto', 'Pag-IBIG ₱100 cap — RA 9679'),
    ('DGD-BIR',   'bir',        true, 'auto', 'BIR TRAIN Law — RA 10963')
ON CONFLICT (deduction_type) DO NOTHING;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_deduction_overrides_employee ON public.deduction_overrides(employee_id);
CREATE INDEX IF NOT EXISTS idx_deduction_overrides_type ON public.deduction_overrides(deduction_type);

-- RLS
ALTER TABLE public.deduction_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deduction_global_defaults ENABLE ROW LEVEL SECURITY;

-- Admin/HR/Finance/Payroll Admin can manage overrides
CREATE POLICY "admin_manage_deduction_overrides" ON public.deduction_overrides
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.employees e
            WHERE e.profile_id = auth.uid()
            AND e.role IN ('admin', 'hr', 'finance', 'payroll_admin')
        )
    );

CREATE POLICY "admin_manage_deduction_global_defaults" ON public.deduction_global_defaults
    FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM public.employees e
            WHERE e.profile_id = auth.uid()
            AND e.role IN ('admin', 'hr', 'finance', 'payroll_admin')
        )
    );

-- Employees can read their own overrides
CREATE POLICY "employee_read_own_overrides" ON public.deduction_overrides
    FOR SELECT
    USING (
        employee_id IN (
            SELECT id FROM public.employees WHERE profile_id = auth.uid()
        )
    );


-- ----------------------------------------------------------------------------
-- SOURCE: 037_fix_deduction_rls.sql
-- ----------------------------------------------------------------------------
-- ═══════════════════════════════════════════════════════════════
-- Migration 037: Fix RLS policies for deduction override tables
--
-- Issue: FOR ALL USING(...) without WITH CHECK blocks INSERT/UPDATE.
-- Fix: Drop old policies, recreate with both USING + WITH CHECK
--       using get_user_role() helper (consistent with 028, 029).
-- ═══════════════════════════════════════════════════════════════

-- ─── deduction_overrides ────────────────────────────────────────
DROP POLICY IF EXISTS "admin_manage_deduction_overrides" ON public.deduction_overrides;
DROP POLICY IF EXISTS "employee_read_own_overrides" ON public.deduction_overrides;

-- Admin/HR/Finance/Payroll Admin: full CRUD
CREATE POLICY deduction_overrides_admin_all
    ON public.deduction_overrides
    FOR ALL
    USING (
        public.get_user_role() IN ('admin', 'hr', 'finance', 'payroll_admin')
    )
    WITH CHECK (
        public.get_user_role() IN ('admin', 'hr', 'finance', 'payroll_admin')
    );

-- Employees can read their own overrides
CREATE POLICY deduction_overrides_employee_select
    ON public.deduction_overrides
    FOR SELECT
    USING (
        employee_id IN (
            SELECT id FROM public.employees WHERE profile_id = auth.uid()
        )
    );

-- ─── deduction_global_defaults ──────────────────────────────────
DROP POLICY IF EXISTS "admin_manage_deduction_global_defaults" ON public.deduction_global_defaults;

-- Admin/HR/Finance/Payroll Admin: full CRUD
CREATE POLICY deduction_global_defaults_admin_all
    ON public.deduction_global_defaults
    FOR ALL
    USING (
        public.get_user_role() IN ('admin', 'hr', 'finance', 'payroll_admin')
    )
    WITH CHECK (
        public.get_user_role() IN ('admin', 'hr', 'finance', 'payroll_admin')
    );

-- All authenticated users can read global defaults (needed to compute payslips)
CREATE POLICY deduction_global_defaults_read
    ON public.deduction_global_defaults
    FOR SELECT
    USING (auth.uid() IS NOT NULL);


-- ----------------------------------------------------------------------------
-- SOURCE: 038_payroll_signature_config.sql
-- ----------------------------------------------------------------------------
-- ─────────────────────────────────────────────────────────────
-- Migration 038: payroll_signature_config
-- Single-row table (id = 'default') storing the authorized
-- signatory details that appear on all printed payslips.
-- ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.payroll_signature_config (
  id              text NOT NULL DEFAULT 'default',
  mode            text NOT NULL DEFAULT 'auto' CHECK (mode IN ('auto', 'manual')),
  signatory_name  text NOT NULL DEFAULT '',
  signatory_title text NOT NULL DEFAULT '',
  signature_data_url text,
  updated_at      timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payroll_signature_config_pkey PRIMARY KEY (id)
);

-- Seed the single default row so upsert always works
INSERT INTO public.payroll_signature_config (id, mode, signatory_name, signatory_title)
VALUES ('default', 'auto', '', '')
ON CONFLICT (id) DO NOTHING;

-- ─── RLS ────────────────────────────────────────────────────
ALTER TABLE public.payroll_signature_config ENABLE ROW LEVEL SECURITY;

-- Payroll admin roles can read and write
CREATE POLICY payroll_sig_admin_all ON public.payroll_signature_config
  FOR ALL
  USING  (public.get_user_role() IN ('admin', 'hr', 'finance', 'payroll_admin'))
  WITH CHECK (public.get_user_role() IN ('admin', 'hr', 'finance', 'payroll_admin'));

-- All authenticated users can read (needed for printing payslips)
CREATE POLICY payroll_sig_read ON public.payroll_signature_config
  FOR SELECT
  USING (auth.uid() IS NOT NULL);


-- ----------------------------------------------------------------------------
-- SOURCE: 039_fix_payroll_fk_cascade.sql
-- ----------------------------------------------------------------------------
-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 039: Fix payroll FK cascade behaviour
--
-- Problem: Deleting payslips or payroll_runs fails when child tables have
-- NOT NULL FK references (loan_deductions, payroll_run_payslips,
-- payroll_adjustments).  Nullable references (loan_balance_history,
-- loan_repayment_schedule, final_pay_computations) also block deletion.
--
-- Fix:
--   • NOT NULL FKs to payslips/runs → ON DELETE CASCADE
--     (when a payslip is deleted, these child records are meaningless)
--   • Nullable FKs to payslips        → ON DELETE SET NULL
--     (preserve the parent row but clear the reference)
-- ─────────────────────────────────────────────────────────────────────────────

-- ── References to payslips ───────────────────────────────────────────────────

-- 1. loan_deductions.payslip_id  (NOT NULL → CASCADE)
-- loan_deductions is created in 07_loans.sql; skip if not yet created.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='loan_deductions') THEN
    ALTER TABLE public.loan_deductions
      DROP CONSTRAINT IF EXISTS fk_ld_payslip,
      ADD  CONSTRAINT fk_ld_payslip
           FOREIGN KEY (payslip_id) REFERENCES public.payslips(id)
           ON DELETE CASCADE;
  END IF;
END $$;

-- 2. payroll_run_payslips.payslip_id  (NOT NULL junction → CASCADE)
ALTER TABLE public.payroll_run_payslips
  DROP CONSTRAINT IF EXISTS payroll_run_payslips_payslip_id_fkey,
  ADD  CONSTRAINT payroll_run_payslips_payslip_id_fkey
       FOREIGN KEY (payslip_id) REFERENCES public.payslips(id)
       ON DELETE CASCADE;

-- 3. payroll_adjustments.reference_payslip_id  (NOT NULL → CASCADE)
ALTER TABLE public.payroll_adjustments
  DROP CONSTRAINT IF EXISTS fk_pa_payslip,
  ADD  CONSTRAINT fk_pa_payslip
       FOREIGN KEY (reference_payslip_id) REFERENCES public.payslips(id)
       ON DELETE CASCADE;

-- 4. loan_balance_history.payslip_id  (nullable → SET NULL)
-- loan_balance_history is created in 07_loans.sql; skip if not yet created.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='loan_balance_history') THEN
    ALTER TABLE public.loan_balance_history
      DROP CONSTRAINT IF EXISTS fk_lbh_payslip,
      ADD  CONSTRAINT fk_lbh_payslip
           FOREIGN KEY (payslip_id) REFERENCES public.payslips(id)
           ON DELETE SET NULL;
  END IF;
END $$;

-- 5. loan_repayment_schedule.payslip_id  (nullable → SET NULL)
-- loan_repayment_schedule is created in 07_loans.sql; skip if not yet created.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='loan_repayment_schedule') THEN
    ALTER TABLE public.loan_repayment_schedule
      DROP CONSTRAINT IF EXISTS fk_lrs_payslip,
      ADD  CONSTRAINT fk_lrs_payslip
           FOREIGN KEY (payslip_id) REFERENCES public.payslips(id)
           ON DELETE SET NULL;
  END IF;
END $$;

-- 6. final_pay_computations.payslip_id  (nullable → SET NULL)
ALTER TABLE public.final_pay_computations
  DROP CONSTRAINT IF EXISTS fk_fpc_payslip,
  ADD  CONSTRAINT fk_fpc_payslip
       FOREIGN KEY (payslip_id) REFERENCES public.payslips(id)
       ON DELETE SET NULL;

-- ── References to payroll_runs ───────────────────────────────────────────────

-- 7. payroll_run_payslips.run_id  (NOT NULL junction → CASCADE)
ALTER TABLE public.payroll_run_payslips
  DROP CONSTRAINT IF EXISTS payroll_run_payslips_run_id_fkey,
  ADD  CONSTRAINT payroll_run_payslips_run_id_fkey
       FOREIGN KEY (run_id) REFERENCES public.payroll_runs(id)
       ON DELETE CASCADE;

-- 8. payroll_adjustments.payroll_run_id  (NOT NULL → CASCADE)
ALTER TABLE public.payroll_adjustments
  DROP CONSTRAINT IF EXISTS fk_pa_run,
  ADD  CONSTRAINT fk_pa_run
       FOREIGN KEY (payroll_run_id) REFERENCES public.payroll_runs(id)
       ON DELETE CASCADE;


-- ----------------------------------------------------------------------------
-- SOURCE: 045_payroll_simplification.sql
-- ----------------------------------------------------------------------------
-- =====================================================
-- Migration 045: Payroll Simplification & Custom Deductions
-- =====================================================
-- Simplifies payslip flow: draft -> published -> signed
-- Simplifies run flow: draft -> locked -> completed
-- Adds custom deduction templates, employee assignments,
-- payslip line items, and employee deduction exemption.
--
-- PERMANENT FIX: Uses DO $$ blocks to detect the actual
-- column types of employees.id and payslips.id at runtime.
-- Handles both text and uuid PKs without manual intervention.
-- Self-validates at the end - rolls back if anything is wrong.
-- =====================================================

BEGIN;

-- STEP 0: Pre-flight - abort if prerequisite tables missing
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='employees') THEN
    RAISE EXCEPTION '[045] ABORTED: public.employees does not exist. Run migrations 001-002 first.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='payslips') THEN
    RAISE EXCEPTION '[045] ABORTED: public.payslips does not exist. Run migration 006 first.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='payroll_runs') THEN
    RAISE EXCEPTION '[045] ABORTED: public.payroll_runs does not exist. Run migration 006 first.';
  END IF;
END $$;

-- STEP 1: Add deduction exemption columns to employees
ALTER TABLE public.employees
  ADD COLUMN IF NOT EXISTS deduction_exempt boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS deduction_exempt_reason text;

-- STEP 2: Create deduction_templates table
CREATE TABLE IF NOT EXISTS public.deduction_templates (
  id text NOT NULL DEFAULT ('DT-' || gen_random_uuid()::text),
  name text NOT NULL,
  type text NOT NULL DEFAULT 'deduction' CHECK (type IN ('deduction', 'allowance')),
  calculation_mode text NOT NULL DEFAULT 'fixed' CHECK (calculation_mode IN ('fixed', 'percentage', 'daily', 'hourly')),
  value numeric NOT NULL DEFAULT 0 CHECK (value >= 0),
  conditions jsonb,
  applies_to_all boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_by text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT deduction_templates_pkey PRIMARY KEY (id)
);

-- STEP 3: Create employee_deduction_assignments (dynamic FK type)
DO $$
DECLARE
  v_emp_id_type text;
BEGIN
  SELECT udt_name INTO STRICT v_emp_id_type
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'employees' AND column_name = 'id';

  RAISE NOTICE '[045] employees.id detected as: %', v_emp_id_type;

  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'employee_deduction_assignments') THEN
    EXECUTE format($ddl$
      CREATE TABLE public.employee_deduction_assignments (
        id text NOT NULL DEFAULT ('EDA-' || gen_random_uuid()::text),
        employee_id %I NOT NULL,
        template_id text NOT NULL,
        override_value numeric,
        effective_from date NOT NULL DEFAULT CURRENT_DATE,
        effective_until date,
        is_active boolean NOT NULL DEFAULT true,
        assigned_by text,
        created_at timestamptz NOT NULL DEFAULT now(),
        updated_at timestamptz NOT NULL DEFAULT now(),
        CONSTRAINT employee_deduction_assignments_pkey PRIMARY KEY (id),
        CONSTRAINT eda_employee_fk FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE,
        CONSTRAINT eda_template_fk FOREIGN KEY (template_id) REFERENCES public.deduction_templates(id) ON DELETE CASCADE
      )
    $ddl$, v_emp_id_type);
    RAISE NOTICE '[045] Created employee_deduction_assignments';
  ELSE
    RAISE NOTICE '[045] employee_deduction_assignments already exists - skipped';
  END IF;
END $$;

-- STEP 4: Create payslip_line_items (dynamic FK type)
DO $$
DECLARE
  v_payslip_id_type text;
BEGIN
  SELECT udt_name INTO STRICT v_payslip_id_type
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'payslips' AND column_name = 'id';

  RAISE NOTICE '[045] payslips.id detected as: %', v_payslip_id_type;

  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'payslip_line_items') THEN
    EXECUTE format($ddl$
      CREATE TABLE public.payslip_line_items (
        id text NOT NULL DEFAULT ('PLI-' || gen_random_uuid()::text),
        payslip_id %I NOT NULL,
        label text NOT NULL,
        type text NOT NULL CHECK (type IN ('earning', 'deduction', 'government', 'loan')),
        amount numeric NOT NULL,
        template_id text,
        calculation_detail text,
        CONSTRAINT payslip_line_items_pkey PRIMARY KEY (id),
        CONSTRAINT pli_payslip_fk FOREIGN KEY (payslip_id) REFERENCES public.payslips(id) ON DELETE CASCADE,
        CONSTRAINT pli_template_fk FOREIGN KEY (template_id) REFERENCES public.deduction_templates(id) ON DELETE SET NULL
      )
    $ddl$, v_payslip_id_type);
    RAISE NOTICE '[045] Created payslip_line_items';
  ELSE
    RAISE NOTICE '[045] payslip_line_items already exists - skipped';
  END IF;
END $$;

-- STEP 5: Add columns to payslips
ALTER TABLE public.payslips
  ADD COLUMN IF NOT EXISTS custom_deductions numeric NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS line_items_json jsonb;

-- STEP 6: Migrate payslip statuses (draft/published/signed)
-- First, drop ALL check constraints on payslips.status (regardless of name)
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE nsp.nspname = 'public'
      AND rel.relname = 'payslips'
      AND con.contype = 'c'
      AND pg_get_constraintdef(con.oid) ILIKE '%status%'
  LOOP
    EXECUTE format('ALTER TABLE public.payslips DROP CONSTRAINT %I', r.conname);
    RAISE NOTICE '[045] Dropped payslips constraint: %', r.conname;
  END LOOP;
END $$;

-- Update statuses to new 3-state values
UPDATE public.payslips SET status = 'draft' WHERE status IN ('issued', 'confirmed');
UPDATE public.payslips SET status = 'signed' WHERE status IN ('paid', 'acknowledged');
-- Catch any unknown statuses by forcing them to 'draft'
UPDATE public.payslips SET status = 'draft' WHERE status NOT IN ('draft', 'published', 'signed');

-- Add new constraint
ALTER TABLE public.payslips ADD CONSTRAINT payslips_status_check CHECK (status IN ('draft', 'published', 'signed'));

-- STEP 7: Migrate payroll_runs statuses (draft/locked/completed)
-- First, drop ALL check constraints on payroll_runs.status (regardless of name)
DO $$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT con.conname
    FROM pg_constraint con
    JOIN pg_class rel ON rel.oid = con.conrelid
    JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
    WHERE nsp.nspname = 'public'
      AND rel.relname = 'payroll_runs'
      AND con.contype = 'c'
      AND pg_get_constraintdef(con.oid) ILIKE '%status%'
  LOOP
    EXECUTE format('ALTER TABLE public.payroll_runs DROP CONSTRAINT %I', r.conname);
    RAISE NOTICE '[045] Dropped payroll_runs constraint: %', r.conname;
  END LOOP;
END $$;

-- Update statuses to new 3-state values
UPDATE public.payroll_runs SET status = 'draft' WHERE status = 'validated';
UPDATE public.payroll_runs SET status = 'completed' WHERE status IN ('published', 'paid');
-- Catch any unknown statuses by forcing them to 'draft'
UPDATE public.payroll_runs SET status = 'draft' WHERE status NOT IN ('draft', 'locked', 'completed');

-- Add new constraint
ALTER TABLE public.payroll_runs ADD CONSTRAINT payroll_runs_status_check CHECK (status IN ('draft', 'locked', 'completed'));
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS completed_at timestamptz;

-- STEP 8: Indexes
CREATE INDEX IF NOT EXISTS idx_deduction_templates_active ON public.deduction_templates(is_active);
CREATE INDEX IF NOT EXISTS idx_eda_employee ON public.employee_deduction_assignments(employee_id);
CREATE INDEX IF NOT EXISTS idx_eda_template ON public.employee_deduction_assignments(template_id);
CREATE INDEX IF NOT EXISTS idx_pli_payslip ON public.payslip_line_items(payslip_id);
CREATE INDEX IF NOT EXISTS idx_employees_deduction_exempt ON public.employees(deduction_exempt) WHERE deduction_exempt = true;

-- STEP 9: RLS Policies (idempotent)
ALTER TABLE public.deduction_templates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS deduction_templates_read_policy ON public.deduction_templates;
CREATE POLICY deduction_templates_read_policy ON public.deduction_templates FOR SELECT USING (true);
DROP POLICY IF EXISTS deduction_templates_write_policy ON public.deduction_templates;
CREATE POLICY deduction_templates_write_policy ON public.deduction_templates FOR ALL USING (
  EXISTS (SELECT 1 FROM public.employees e WHERE e.profile_id = auth.uid() AND e.role IN ('admin', 'hr', 'finance', 'payroll_admin'))
);

ALTER TABLE public.employee_deduction_assignments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS eda_admin_policy ON public.employee_deduction_assignments;
CREATE POLICY eda_admin_policy ON public.employee_deduction_assignments FOR ALL USING (
  EXISTS (SELECT 1 FROM public.employees e WHERE e.profile_id = auth.uid() AND e.role IN ('admin', 'hr', 'finance', 'payroll_admin'))
);
DROP POLICY IF EXISTS eda_employee_read_policy ON public.employee_deduction_assignments;
CREATE POLICY eda_employee_read_policy ON public.employee_deduction_assignments FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.employees e WHERE e.profile_id = auth.uid() AND e.id = employee_id)
);

ALTER TABLE public.payslip_line_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS pli_admin_policy ON public.payslip_line_items;
CREATE POLICY pli_admin_policy ON public.payslip_line_items FOR ALL USING (
  EXISTS (SELECT 1 FROM public.employees e WHERE e.profile_id = auth.uid() AND e.role IN ('admin', 'hr', 'finance', 'payroll_admin'))
);
DROP POLICY IF EXISTS pli_employee_read_policy ON public.payslip_line_items;
CREATE POLICY pli_employee_read_policy ON public.payslip_line_items FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.payslips p JOIN public.employees e ON e.id = p.employee_id WHERE p.id = payslip_id AND e.profile_id = auth.uid())
);

-- STEP 10: Self-validation (rolls back on failure)
DO $$
DECLARE
  v_eda_type text;
  v_emp_type text;
  v_pli_type text;
  v_ps_type  text;
  v_count    integer;
BEGIN
  -- 10a. All 3 new tables exist
  SELECT COUNT(*) INTO v_count FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name IN ('deduction_templates','employee_deduction_assignments','payslip_line_items');
  IF v_count <> 3 THEN RAISE EXCEPTION '[045 VALIDATE] Expected 3 new tables, found %', v_count; END IF;

  -- 10b. FK type matches: eda.employee_id = employees.id
  SELECT udt_name INTO v_eda_type FROM information_schema.columns WHERE table_schema='public' AND table_name='employee_deduction_assignments' AND column_name='employee_id';
  SELECT udt_name INTO v_emp_type FROM information_schema.columns WHERE table_schema='public' AND table_name='employees' AND column_name='id';
  IF v_eda_type IS DISTINCT FROM v_emp_type THEN RAISE EXCEPTION '[045 VALIDATE] Type mismatch: eda.employee_id(%) != employees.id(%)', v_eda_type, v_emp_type; END IF;

  -- 10c. FK type matches: pli.payslip_id = payslips.id
  SELECT udt_name INTO v_pli_type FROM information_schema.columns WHERE table_schema='public' AND table_name='payslip_line_items' AND column_name='payslip_id';
  SELECT udt_name INTO v_ps_type FROM information_schema.columns WHERE table_schema='public' AND table_name='payslips' AND column_name='id';
  IF v_pli_type IS DISTINCT FROM v_ps_type THEN RAISE EXCEPTION '[045 VALIDATE] Type mismatch: pli.payslip_id(%) != payslips.id(%)', v_pli_type, v_ps_type; END IF;

  -- 10d. All 5 indexes
  SELECT COUNT(*) INTO v_count FROM pg_indexes WHERE schemaname='public' AND indexname IN ('idx_deduction_templates_active','idx_eda_employee','idx_eda_template','idx_pli_payslip','idx_employees_deduction_exempt');
  IF v_count <> 5 THEN RAISE EXCEPTION '[045 VALIDATE] Expected 5 indexes, found %', v_count; END IF;

  -- 10e. At least 6 RLS policies
  SELECT COUNT(*) INTO v_count FROM pg_policies WHERE schemaname='public' AND tablename IN ('deduction_templates','employee_deduction_assignments','payslip_line_items');
  IF v_count < 6 THEN RAISE EXCEPTION '[045 VALIDATE] Expected >= 6 RLS policies, found %', v_count; END IF;

  -- 10f. New columns exist
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='employees' AND column_name='deduction_exempt') THEN
    RAISE EXCEPTION '[045 VALIDATE] employees.deduction_exempt missing';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='payslips' AND column_name='custom_deductions') THEN
    RAISE EXCEPTION '[045 VALIDATE] payslips.custom_deductions missing';
  END IF;

  -- 10g. No stale statuses
  IF EXISTS (SELECT 1 FROM public.payslips WHERE status NOT IN ('draft','published','signed') LIMIT 1) THEN
    RAISE EXCEPTION '[045 VALIDATE] Stale payslip statuses found';
  END IF;
  IF EXISTS (SELECT 1 FROM public.payroll_runs WHERE status NOT IN ('draft','locked','completed') LIMIT 1) THEN
    RAISE EXCEPTION '[045 VALIDATE] Stale payroll_run statuses found';
  END IF;

  RAISE NOTICE '[045] ALL 7 VALIDATIONS PASSED';
END $$;

COMMIT;


-- ----------------------------------------------------------------------------
-- SOURCE: 048_payroll_payment_proof.sql
-- ----------------------------------------------------------------------------
-- Migration: 048_payroll_payment_proof.sql
-- Adds payment proof support for payslips:
-- - payment_proof_url: URL to uploaded proof image (Supabase Storage)
-- - cash_amount: For cash payments, store actual amount given

-- Add columns to payslips
ALTER TABLE payslips
ADD COLUMN IF NOT EXISTS payment_proof_url text,
ADD COLUMN IF NOT EXISTS cash_amount numeric;

-- Add check constraint for payment method
ALTER TABLE payslips
DROP CONSTRAINT IF EXISTS payslips_payment_method_check;

ALTER TABLE payslips
ADD CONSTRAINT payslips_payment_method_check 
CHECK (payment_method IS NULL OR payment_method = ANY (ARRAY['bank_transfer'::text, 'gcash'::text, 'cash'::text, 'check'::text]));

-- Create storage bucket for payment proofs if not exists
-- Note: This needs to be run via Supabase Dashboard or CLI since SQL doesn't directly create buckets
-- INSERT INTO storage.buckets (id, name, public)
-- VALUES ('payment-proofs', 'payment-proofs', false)
-- ON CONFLICT (id) DO NOTHING;

-- RLS policy for payment proofs storage (to be configured in Supabase Dashboard):
-- - Admin/Finance/Payroll_Admin can upload (INSERT)
-- - Employees can view their own payslip's proof (SELECT where payslip.employee_id matches)

COMMENT ON COLUMN payslips.payment_proof_url IS 'URL to uploaded payment proof image in Supabase Storage';
COMMENT ON COLUMN payslips.cash_amount IS 'Actual cash amount given (for cash payments)';
COMMENT ON COLUMN payslips.bank_reference_id IS 'Reference number/ID: Bank Transfer ref, GCash ref ID, Check number';


-- ----------------------------------------------------------------------------
-- SOURCE: 054_payslip_payment_hold.sql
-- ----------------------------------------------------------------------------
-- Add individual payment hold status for Option B payroll flow.
-- Unsigned employees can be held without blocking signed employees from payment.

ALTER TABLE public.payslips
DROP CONSTRAINT IF EXISTS payslips_status_check;

UPDATE public.payslips
SET status = 'published'
WHERE status NOT IN ('draft', 'published', 'signed', 'paid', 'payment_hold');

ALTER TABLE public.payslips
ADD CONSTRAINT payslips_status_check
CHECK (status IN ('draft', 'published', 'signed', 'paid', 'payment_hold'));

