-- ============================================================================
-- 08_tasks_projects_messaging.sql
-- ----------------------------------------------------------------------------
-- Consolidated from legacy migrations: 008, 010, 027, 029, 031, 032, 046, 060
-- Apply order: run this file in the same numeric order as the file name.
-- Generated by scripts/build-migrations-v2.ps1 â€” DO NOT EDIT BY HAND.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SOURCE: 008_tasks_messaging.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 008_tasks_messaging.sql
-- Task groups, tasks, completions, comments, announcements,
-- text channels, channel messages
-- ============================================================

-- Task Groups
CREATE TABLE IF NOT EXISTS public.task_groups (
    id                      text PRIMARY KEY,
    name                    text NOT NULL,
    description             text,
    project_id              text,
    created_by              text NOT NULL,
    member_employee_ids     text[] NOT NULL DEFAULT '{}',
    announcement_permission text NOT NULL DEFAULT 'admin_only'
                            CHECK (announcement_permission IN ('admin_only','group_leads','all_members')),
    created_at              timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.task_groups ENABLE ROW LEVEL SECURITY;

-- Tasks
CREATE TABLE IF NOT EXISTS public.tasks (
    id                  text PRIMARY KEY,
    group_id            text NOT NULL REFERENCES public.task_groups(id) ON DELETE CASCADE,
    title               text NOT NULL,
    description         text NOT NULL DEFAULT '',
    priority            text NOT NULL DEFAULT 'medium'
                        CHECK (priority IN ('low','medium','high','urgent')),
    status              text NOT NULL DEFAULT 'open'
                        CHECK (status IN ('open','in_progress','submitted','verified','rejected','cancelled')),
    due_date            date,
    assigned_to         text[] NOT NULL DEFAULT '{}',
    created_by          text NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    updated_at          timestamptz NOT NULL DEFAULT now(),
    completion_required boolean NOT NULL DEFAULT false,
    tags                text[] DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_tasks_group ON public.tasks(group_id);
CREATE INDEX IF NOT EXISTS idx_tasks_status ON public.tasks(status);

ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS set_tasks_updated_at ON public.tasks;
CREATE TRIGGER set_tasks_updated_at
    BEFORE UPDATE ON public.tasks
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Task Completion Reports
CREATE TABLE IF NOT EXISTS public.task_completion_reports (
    id                  text PRIMARY KEY,
    task_id             text NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
    employee_id         text NOT NULL,
    photo_data_url      text,
    gps_lat             double precision,
    gps_lng             double precision,
    gps_accuracy_meters double precision,
    reverse_geo_address text,
    notes               text,
    submitted_at        timestamptz NOT NULL DEFAULT now(),
    verified_by         text,
    verified_at         timestamptz,
    rejection_reason    text
);

CREATE INDEX IF NOT EXISTS idx_tcr_task ON public.task_completion_reports(task_id);

ALTER TABLE public.task_completion_reports ENABLE ROW LEVEL SECURITY;

-- Task Comments
CREATE TABLE IF NOT EXISTS public.task_comments (
    id              text PRIMARY KEY,
    task_id         text NOT NULL REFERENCES public.tasks(id) ON DELETE CASCADE,
    employee_id     text NOT NULL,
    message         text NOT NULL,
    attachment_url  text,
    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tc_task ON public.task_comments(task_id);

ALTER TABLE public.task_comments ENABLE ROW LEVEL SECURITY;

-- ─── Messaging ───────────────────────────────────────────────

-- Announcements
CREATE TABLE IF NOT EXISTS public.announcements (
    id                  text PRIMARY KEY,
    subject             text NOT NULL,
    body                text NOT NULL,
    channel             text NOT NULL DEFAULT 'in_app'
                        CHECK (channel IN ('email','whatsapp','sms','in_app')),
    scope               text NOT NULL DEFAULT 'all_employees'
                        CHECK (scope IN ('all_employees','selected_employees','task_group','task_assignees')),
    target_employee_ids text[],
    target_group_id     text,
    target_task_id      text,
    sent_by             text NOT NULL,
    sent_at             timestamptz NOT NULL DEFAULT now(),
    status              text NOT NULL DEFAULT 'sent'
                        CHECK (status IN ('sent','delivered','read','failed','simulated')),
    read_by             text[] NOT NULL DEFAULT '{}',
    attachment_url      text
);

ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

-- Text Channels
CREATE TABLE IF NOT EXISTS public.text_channels (
    id                  text PRIMARY KEY,
    name                text NOT NULL,
    group_id            text,
    member_employee_ids text[] NOT NULL DEFAULT '{}',
    created_by          text NOT NULL,
    created_at          timestamptz NOT NULL DEFAULT now(),
    is_archived         boolean NOT NULL DEFAULT false
);

ALTER TABLE public.text_channels ENABLE ROW LEVEL SECURITY;

-- Channel Messages
CREATE TABLE IF NOT EXISTS public.channel_messages (
    id              text PRIMARY KEY,
    channel_id      text NOT NULL REFERENCES public.text_channels(id) ON DELETE CASCADE,
    employee_id     text NOT NULL,
    message         text NOT NULL,
    attachment_url  text,
    created_at      timestamptz NOT NULL DEFAULT now(),
    edited_at       timestamptz,
    read_by         text[] NOT NULL DEFAULT '{}'
);

CREATE INDEX IF NOT EXISTS idx_cm_channel ON public.channel_messages(channel_id);
CREATE INDEX IF NOT EXISTS idx_cm_created ON public.channel_messages(created_at);

ALTER TABLE public.channel_messages ENABLE ROW LEVEL SECURITY;


-- ----------------------------------------------------------------------------
-- SOURCE: 010_projects_timesheets_settings.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 010_projects_timesheets_settings.sql
-- Projects, timesheets, attendance rule sets, calendar events,
-- kiosk, location, appearance, gov table versions, custom pages
-- ============================================================

-- Projects
CREATE TABLE IF NOT EXISTS public.projects (
    id                      text PRIMARY KEY,
    name                    text NOT NULL,
    description             text,
    location_lat            double precision,
    location_lng            double precision,
    location_radius         double precision,
    assigned_employee_ids   text[] NOT NULL DEFAULT '{}',
    verification_method     text CHECK (verification_method IN ('face_only','qr_only','face_or_qr','manual_only')) DEFAULT 'face_or_qr',
    require_geofence        boolean DEFAULT true,
    geofence_radius_meters  integer DEFAULT 100,
    qr_secret               text,
    qr_enabled              boolean NOT NULL DEFAULT true,
    status                  text DEFAULT 'active'
                            CHECK (status IN ('active','completed','on_hold')),
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- Attendance Rule Sets (§3 timesheet computation)
CREATE TABLE IF NOT EXISTS public.attendance_rule_sets (
    id                          text PRIMARY KEY,
    name                        text NOT NULL,
    standard_hours_per_day      numeric NOT NULL DEFAULT 8,
    grace_minutes               integer NOT NULL DEFAULT 15,
    rounding_policy             text NOT NULL DEFAULT 'none'
                                CHECK (rounding_policy IN ('none','nearest_15','nearest_30')),
    overtime_requires_approval  boolean NOT NULL DEFAULT true,
    night_diff_start            text,
    night_diff_end              text,
    holiday_multiplier          numeric NOT NULL DEFAULT 1.0
);

ALTER TABLE public.attendance_rule_sets ENABLE ROW LEVEL SECURITY;

-- Timesheets (daily computed)
CREATE TABLE IF NOT EXISTS public.timesheets (
    id                  text PRIMARY KEY,
    employee_id         text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    date                date NOT NULL,
    rule_set_id         text,
    shift_id            text,
    regular_hours       numeric NOT NULL DEFAULT 0,
    overtime_hours      numeric NOT NULL DEFAULT 0,
    night_diff_hours    numeric NOT NULL DEFAULT 0,
    total_hours         numeric NOT NULL DEFAULT 0,
    late_minutes        integer NOT NULL DEFAULT 0,
    undertime_minutes   integer NOT NULL DEFAULT 0,
    segments            jsonb NOT NULL DEFAULT '[]',
    status              text NOT NULL DEFAULT 'computed'
                        CHECK (status IN ('computed','submitted','approved','rejected')),
    computed_at         timestamptz NOT NULL DEFAULT now(),
    approved_by         text,
    approved_at         timestamptz,
    UNIQUE (employee_id, date)
);

CREATE INDEX IF NOT EXISTS idx_ts_employee ON public.timesheets(employee_id);
CREATE INDEX IF NOT EXISTS idx_ts_date ON public.timesheets(date);

ALTER TABLE public.timesheets ENABLE ROW LEVEL SECURITY;

-- Calendar Events
CREATE TABLE IF NOT EXISTS public.calendar_events (
    id      text PRIMARY KEY,
    title   text NOT NULL,
    time    text NOT NULL,
    date    date NOT NULL,
    type    text
);

ALTER TABLE public.calendar_events ENABLE ROW LEVEL SECURITY;

-- Kiosk Devices
CREATE TABLE IF NOT EXISTS public.kiosk_devices (
    id              text PRIMARY KEY,
    name            text NOT NULL,
    registered_at   timestamptz NOT NULL DEFAULT now(),
    project_id      text,
    is_active       boolean NOT NULL DEFAULT true
);

ALTER TABLE public.kiosk_devices ENABLE ROW LEVEL SECURITY;

-- QR Tokens (short-lived)
CREATE TABLE IF NOT EXISTS public.qr_tokens (
    id          text PRIMARY KEY,
    device_id   text NOT NULL REFERENCES public.kiosk_devices(id) ON DELETE CASCADE,
    token       text NOT NULL UNIQUE,
    created_at  timestamptz NOT NULL DEFAULT now(),
    expires_at  timestamptz NOT NULL,
    used        boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_qr_device ON public.qr_tokens(device_id);
CREATE INDEX IF NOT EXISTS idx_qr_expires ON public.qr_tokens(expires_at);

ALTER TABLE public.qr_tokens ENABLE ROW LEVEL SECURITY;

-- Location Tracking Config (singleton)
CREATE TABLE IF NOT EXISTS public.location_config (
    id                              text PRIMARY KEY DEFAULT 'default',
    enabled                         boolean NOT NULL DEFAULT true,
    ping_interval_minutes           integer NOT NULL DEFAULT 5,
    require_location                boolean NOT NULL DEFAULT true,
    warn_employee_out_of_fence      boolean NOT NULL DEFAULT true,
    alert_admin_out_of_fence        boolean NOT NULL DEFAULT true,
    alert_admin_location_disabled   boolean NOT NULL DEFAULT true,
    track_during_breaks             boolean NOT NULL DEFAULT false,
    retain_days                     integer NOT NULL DEFAULT 90,
    require_selfie                  boolean NOT NULL DEFAULT false,
    selfie_required_projects        text[] DEFAULT '{}',
    selfie_max_age                  integer NOT NULL DEFAULT 120,
    show_reverse_geocode            boolean NOT NULL DEFAULT true,
    selfie_compression_quality      numeric NOT NULL DEFAULT 0.7,
    lunch_duration                  integer NOT NULL DEFAULT 60,
    lunch_geofence_required         boolean NOT NULL DEFAULT false,
    lunch_overtime_threshold        integer NOT NULL DEFAULT 0,
    alert_admin_on_geofence_violation boolean NOT NULL DEFAULT true,
    allowed_breaks_per_day          integer NOT NULL DEFAULT 2,
    break_grace_period              integer NOT NULL DEFAULT 5,
    updated_at                      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.location_config ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS set_location_config_updated_at ON public.location_config;
CREATE TRIGGER set_location_config_updated_at
    BEFORE UPDATE ON public.location_config
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Location Pings
CREATE TABLE IF NOT EXISTS public.location_pings (
    id                  text PRIMARY KEY,
    employee_id         text NOT NULL,
    timestamp           timestamptz NOT NULL DEFAULT now(),
    lat                 double precision NOT NULL,
    lng                 double precision NOT NULL,
    accuracy_meters     double precision NOT NULL,
    within_geofence     boolean NOT NULL DEFAULT true,
    project_id          text,
    distance_from_site  double precision,
    source              text NOT NULL DEFAULT 'auto'
                        CHECK (source IN ('auto','manual','break_end'))
);

CREATE INDEX IF NOT EXISTS idx_pings_employee ON public.location_pings(employee_id);
CREATE INDEX IF NOT EXISTS idx_pings_timestamp ON public.location_pings(timestamp);

ALTER TABLE public.location_pings ENABLE ROW LEVEL SECURITY;

-- Site Survey Photos
CREATE TABLE IF NOT EXISTS public.site_survey_photos (
    id                  text PRIMARY KEY,
    event_id            text NOT NULL,
    employee_id         text NOT NULL,
    photo_data_url      text NOT NULL,
    gps_lat             double precision NOT NULL,
    gps_lng             double precision NOT NULL,
    gps_accuracy_meters double precision NOT NULL,
    reverse_geo_address text,
    captured_at         timestamptz NOT NULL DEFAULT now(),
    geofence_pass       boolean,
    project_id          text
);

CREATE INDEX IF NOT EXISTS idx_ssp_employee ON public.site_survey_photos(employee_id);

ALTER TABLE public.site_survey_photos ENABLE ROW LEVEL SECURITY;

-- Break Records
CREATE TABLE IF NOT EXISTS public.break_records (
    id                  text PRIMARY KEY,
    employee_id         text NOT NULL,
    date                date NOT NULL,
    break_type          text NOT NULL DEFAULT 'lunch'
                        CHECK (break_type IN ('lunch','other')),
    start_time          text NOT NULL,
    end_time            text,
    start_lat           double precision,
    start_lng           double precision,
    end_lat             double precision,
    end_lng             double precision,
    end_geofence_pass   boolean,
    distance_from_site  double precision,
    duration            integer,
    overtime            boolean DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_br_employee ON public.break_records(employee_id);

ALTER TABLE public.break_records ENABLE ROW LEVEL SECURITY;

-- Appearance Config (singleton — company branding)
CREATE TABLE IF NOT EXISTS public.appearance_config (
    id                  text PRIMARY KEY DEFAULT 'default',
    company_name        text NOT NULL DEFAULT 'Premium Outlets',
    company_logo        text,
    sidebar_color       text DEFAULT '#1e293b',
    primary_color       text DEFAULT '#3b82f6',
    login_heading       text,
    login_sub_heading   text,
    login_background    text,
    login_logo          text,
    module_flags        jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.appearance_config ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS set_appearance_config_updated_at ON public.appearance_config;
CREATE TRIGGER set_appearance_config_updated_at
    BEFORE UPDATE ON public.appearance_config
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Government Table Versions (§7)
CREATE TABLE IF NOT EXISTS public.gov_table_versions (
    id              text PRIMARY KEY,
    table_name      text NOT NULL CHECK (table_name IN ('sss','philhealth','pagibig','tax')),
    version         text NOT NULL,
    effective_date  date NOT NULL,
    snapshot_json   text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.gov_table_versions ENABLE ROW LEVEL SECURITY;

-- Custom Roles Dashboard Layouts (stored as JSONB per role)
CREATE TABLE IF NOT EXISTS public.dashboard_layouts (
    role_id     text PRIMARY KEY REFERENCES public.roles_custom(id) ON DELETE CASCADE,
    widgets     jsonb NOT NULL DEFAULT '[]',
    updated_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.dashboard_layouts ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS set_dashboard_layouts_updated_at ON public.dashboard_layouts;
CREATE TRIGGER set_dashboard_layouts_updated_at
    BEFORE UPDATE ON public.dashboard_layouts
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_updated_at();

-- Custom Pages (page builder)
CREATE TABLE IF NOT EXISTS public.custom_pages (
    id              text PRIMARY KEY,
    title           text NOT NULL,
    slug            text NOT NULL UNIQUE,
    icon            text NOT NULL DEFAULT 'file',
    description     text,
    allowed_roles   text[] NOT NULL DEFAULT '{}',
    widgets         jsonb NOT NULL DEFAULT '[]',
    show_in_sidebar boolean NOT NULL DEFAULT true,
    "order"         integer NOT NULL DEFAULT 0,
    created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.custom_pages ENABLE ROW LEVEL SECURITY;


-- ----------------------------------------------------------------------------
-- SOURCE: 027_project_constraints.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 027_project_constraints.sql
-- 1. Add missing columns to projects table
-- 2. Enforce 1-project-per-employee at the DB level via trigger
-- ============================================================

-- ─── Add missing columns ─────────────────────────────────────

ALTER TABLE public.projects
    ADD COLUMN IF NOT EXISTS location_address    text,
    ADD COLUMN IF NOT EXISTS verification_method text DEFAULT 'face_or_qr'
        CHECK (verification_method IN ('face_only','qr_only','face_or_qr','manual_only')),
    ADD COLUMN IF NOT EXISTS require_geofence    boolean NOT NULL DEFAULT true,
    ADD COLUMN IF NOT EXISTS geofence_radius_meters double precision;

-- ─── Function: enforce 1 project per employee ────────────────
--
-- Before any INSERT or UPDATE on projects, check that none of the
-- NEW row's assigned_employee_ids already appear in any OTHER project.
-- If they do, strip them from the OTHER project(s) atomically.
--
-- This mirrors the Zustand store logic: "move" the employee instead
-- of blocking the operation, so the app's intent is always honoured.

CREATE OR REPLACE FUNCTION public.enforce_one_project_per_employee()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    emp_id text;
BEGIN
    -- For each employee being assigned to the NEW row...
    FOREACH emp_id IN ARRAY NEW.assigned_employee_ids
    LOOP
        -- Remove that employee from every OTHER project row
        UPDATE public.projects
        SET assigned_employee_ids = array_remove(assigned_employee_ids, emp_id)
        WHERE id <> NEW.id
          AND emp_id = ANY(assigned_employee_ids);
    END LOOP;

    RETURN NEW;
END;
$$;

-- Drop old version if exists, then recreate
DROP TRIGGER IF EXISTS trg_one_project_per_employee ON public.projects;

CREATE TRIGGER trg_one_project_per_employee
    BEFORE INSERT OR UPDATE OF assigned_employee_ids
    ON public.projects
    FOR EACH ROW
    EXECUTE FUNCTION public.enforce_one_project_per_employee();

-- ─── Grant execute on the function ───────────────────────────

GRANT EXECUTE ON FUNCTION public.enforce_one_project_per_employee() TO authenticated;
GRANT EXECUTE ON FUNCTION public.enforce_one_project_per_employee() TO service_role;


-- ----------------------------------------------------------------------------
-- SOURCE: 029_project_assignments_junction.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 029_project_assignments_junction.sql
-- Replace projects.assigned_employee_ids text[] with proper
-- junction table for FK enforcement and indexing.
-- ============================================================

-- ─── Junction table ──────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.project_assignments (
    project_id   text NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    employee_id  text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
    assigned_at  timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (project_id, employee_id)
);

CREATE INDEX IF NOT EXISTS idx_pa_employee ON public.project_assignments(employee_id);

ALTER TABLE public.project_assignments ENABLE ROW LEVEL SECURITY;

-- RLS: readable by all (matches projects table), writable by admin/hr/supervisor
CREATE POLICY "project_assignments_read"
    ON public.project_assignments
    FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "project_assignments_write"
    ON public.project_assignments
    FOR ALL
    TO authenticated
    USING (
        public.get_user_role() IN ('admin', 'hr', 'supervisor')
    )
    WITH CHECK (
        public.get_user_role() IN ('admin', 'hr', 'supervisor')
    );

-- ─── Migrate existing data ───────────────────────────────────

INSERT INTO public.project_assignments (project_id, employee_id)
SELECT p.id, unnest(p.assigned_employee_ids)
FROM public.projects p
WHERE array_length(p.assigned_employee_ids, 1) > 0
ON CONFLICT DO NOTHING;

-- ─── Update the enforce_one_project_per_employee trigger ─────
-- Now operates on the junction table instead of array column.

CREATE OR REPLACE FUNCTION public.enforce_one_project_per_employee()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    -- When an assignment is inserted, remove that employee
    -- from any OTHER project (enforce 1 project per employee).
    DELETE FROM public.project_assignments
    WHERE employee_id = NEW.employee_id
      AND project_id <> NEW.project_id;

    RETURN NEW;
END;
$$;

-- Drop old trigger (was on projects table)
DROP TRIGGER IF EXISTS trg_one_project_per_employee ON public.projects;

-- New trigger on the junction table
DROP TRIGGER IF EXISTS trg_one_project_per_employee ON public.project_assignments;
CREATE TRIGGER trg_one_project_per_employee
    BEFORE INSERT
    ON public.project_assignments
    FOR EACH ROW
    EXECUTE FUNCTION public.enforce_one_project_per_employee();

-- ─── Keep old column but mark deprecated ─────────────────────
COMMENT ON COLUMN public.projects.assigned_employee_ids
    IS 'DEPRECATED — use project_assignments junction table. Will be removed in a future migration.';


-- ----------------------------------------------------------------------------
-- SOURCE: 031_tasks_project_id.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 031_tasks_project_id.sql
-- Add project_id column to tasks table so tasks can be
-- directly linked to a project (in addition to via group).
-- ============================================================

ALTER TABLE public.tasks
    ADD COLUMN IF NOT EXISTS project_id text
    REFERENCES public.projects(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_tasks_project ON public.tasks(project_id);


-- ----------------------------------------------------------------------------
-- SOURCE: 032_task_tags.sql
-- ----------------------------------------------------------------------------
-- ─── Task Tags Table ──────────────────────────────────────────
-- Provides a managed registry of tags that admins can define,
-- each with a display name and a hex colour.  Tasks reference
-- tags by name (string[]), so this table is purely metadata.

CREATE TABLE IF NOT EXISTS public.task_tags (
    id          text        PRIMARY KEY,
    name        text        NOT NULL UNIQUE,
    color       text        NOT NULL DEFAULT '#6366f1',
    created_by  text        NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now()
);

-- Full access for authenticated users (admin manages in UI)
ALTER TABLE public.task_tags ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read task_tags"
    ON public.task_tags FOR SELECT
    TO authenticated
    USING (true);

CREATE POLICY "Authenticated users can insert task_tags"
    ON public.task_tags FOR INSERT
    TO authenticated
    WITH CHECK (true);

CREATE POLICY "Authenticated users can update task_tags"
    ON public.task_tags FOR UPDATE
    TO authenticated
    USING (true);

CREATE POLICY "Authenticated users can delete task_tags"
    ON public.task_tags FOR DELETE
    TO authenticated
    USING (true);

-- Index for quick name lookups / auto-complete
CREATE INDEX IF NOT EXISTS idx_task_tags_name ON public.task_tags (lower(name));


-- ----------------------------------------------------------------------------
-- SOURCE: 046_text_channels_realtime.sql
-- ----------------------------------------------------------------------------
-- Migration 046: Enable Supabase Realtime for text_channels
--
-- The text_channels table was missing from realtime publication.
-- This enables real-time channel creation, updates, and deletions
-- to sync across all connected clients.

DO $$
BEGIN
  -- Set REPLICA IDENTITY FULL for complete UPDATE payloads
  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname = 'text_channels' AND c.relkind = 'r'
  ) THEN
    ALTER TABLE public.text_channels REPLICA IDENTITY FULL;
  END IF;

  -- Add to supabase_realtime publication
  IF EXISTS (
    SELECT 1 FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public' AND c.relname = 'text_channels' AND c.relkind = 'r'
  ) THEN
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.text_channels;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
  END IF;
END;
$$;


-- ----------------------------------------------------------------------------
-- SOURCE: 060_tasks_schema_updates.sql
-- ----------------------------------------------------------------------------
-- 060_tasks_schema_updates
-- Migration: Make group_id nullable + add start_date
-- Date: 2026-05-11

-- ======================================================================

-- == Make group_id nullable (tasks can exist without a group) =======
ALTER TABLE public.tasks ALTER COLUMN group_id DROP NOT NULL;

-- == Add start_date column ===========================================
ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS start_date date;

-- ─── Seed: face-only demo project (moved from 04_attendance_and_kiosk.sql) ───
INSERT INTO public.projects (
    id, name, description,
    location_lat, location_lng, location_radius,
    assigned_employee_ids,
    verification_method,
    require_geofence,
    geofence_radius_meters,
    status,
    created_at
)
VALUES (
    'PRJ006',
    'Makati Security Post – Face Check-in',
    'Makati CBD security post using face recognition for attendance. Demo account for testing biometric check-in.',
    14.5567,
    121.0178,
    300,
    ARRAY['EMP029'],
    'face_only',
    true,
    300,
    'active',
    '2026-01-15T00:00:00Z'
)
ON CONFLICT (id) DO UPDATE SET
    name                    = EXCLUDED.name,
    assigned_employee_ids   = EXCLUDED.assigned_employee_ids,
    verification_method     = EXCLUDED.verification_method,
    updated_at              = NOW();

INSERT INTO public.project_assignments (project_id, employee_id, assigned_at)
VALUES ('PRJ006', 'EMP029', NOW())
ON CONFLICT (project_id, employee_id) DO NOTHING;

