-- ============================================================================
-- 09_notifications_and_audit.sql
-- ----------------------------------------------------------------------------
-- Consolidated from legacy migrations: 009, 019, 021, 044, 047, 052
-- Apply order: run this file in the same numeric order as the file name.
-- Generated by scripts/build-migrations-v2.ps1 â€” DO NOT EDIT BY HAND.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SOURCE: 009_audit_notifications.sql
-- ----------------------------------------------------------------------------
-- ============================================================
-- 009_audit_notifications.sql
-- Audit logs, notification logs, notification rules
-- ============================================================

-- Audit Logs (immutable — append only)
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id              text PRIMARY KEY,
    entity_type     text NOT NULL,
    entity_id       text NOT NULL,
    action          text NOT NULL,
    performed_by    text NOT NULL,
    timestamp       timestamptz NOT NULL DEFAULT now(),
    reason          text,
    before_snapshot jsonb,
    after_snapshot  jsonb
);

CREATE INDEX IF NOT EXISTS idx_audit_entity ON public.audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_action ON public.audit_logs(action);
CREATE INDEX IF NOT EXISTS idx_audit_performer ON public.audit_logs(performed_by);
CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON public.audit_logs(timestamp);

ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Notification Logs
CREATE TABLE IF NOT EXISTS public.notification_logs (
    id              text PRIMARY KEY,
    employee_id     text NOT NULL,
    type            text NOT NULL,
    channel         text NOT NULL DEFAULT 'in_app'
                    CHECK (channel IN ('email','sms','both','in_app')),
    subject         text NOT NULL,
    body            text NOT NULL,
    sent_at         timestamptz NOT NULL DEFAULT now(),
    status          text NOT NULL DEFAULT 'sent'
                    CHECK (status IN ('sent','failed','simulated')),
    recipient_email text,
    recipient_phone text,
    error_message   text
);

CREATE INDEX IF NOT EXISTS idx_notif_employee ON public.notification_logs(employee_id);
CREATE INDEX IF NOT EXISTS idx_notif_type ON public.notification_logs(type);

ALTER TABLE public.notification_logs ENABLE ROW LEVEL SECURITY;

-- Notification Rules (admin configurable)
CREATE TABLE IF NOT EXISTS public.notification_rules (
    id                text PRIMARY KEY,
    trigger           text NOT NULL,
    enabled           boolean NOT NULL DEFAULT true,
    channel           text NOT NULL DEFAULT 'in_app'
                      CHECK (channel IN ('email','sms','both','in_app')),
    recipient_roles   text[] NOT NULL DEFAULT '{}',
    timing            text NOT NULL DEFAULT 'immediate'
                      CHECK (timing IN ('immediate','scheduled')),
    schedule_time     text,
    reminder_days     integer[],
    subject_template  text NOT NULL,
    body_template     text NOT NULL,
    sms_template      text
);

ALTER TABLE public.notification_rules ENABLE ROW LEVEL SECURITY;


-- ----------------------------------------------------------------------------
-- SOURCE: 019_extend_event_types.sql
-- ----------------------------------------------------------------------------
-- Migration 019: Extend attendance_events.event_type to support admin overrides
-- Adds OVERRIDE and BULK_OVERRIDE event types for audit trail

ALTER TABLE public.attendance_events
  DROP CONSTRAINT IF EXISTS attendance_events_event_type_check;

ALTER TABLE public.attendance_events
  ADD CONSTRAINT attendance_events_event_type_check
  CHECK (event_type IN ('IN','OUT','BREAK_START','BREAK_END','OVERRIDE','BULK_OVERRIDE'));


-- ----------------------------------------------------------------------------
-- SOURCE: 021_expand_event_types.sql
-- ----------------------------------------------------------------------------
-- Migration 021: Expand attendance_events.event_type for full admin audit trail
-- Adds all admin action event types to support comprehensive event ledger

ALTER TABLE public.attendance_events
  DROP CONSTRAINT IF EXISTS attendance_events_event_type_check;

ALTER TABLE public.attendance_events
  ADD CONSTRAINT attendance_events_event_type_check
  CHECK (event_type IN (
    'IN', 'OUT', 'BREAK_START', 'BREAK_END',
    'OVERRIDE', 'BULK_OVERRIDE', 'MARK_ABSENT', 'MARK_PRESENT',
    'OT_APPROVED', 'OT_REJECTED', 'OT_SUBMITTED',
    'EXCEPTION_RESOLVED', 'EXCEPTION_SCANNED',
    'HOLIDAY_ADDED', 'HOLIDAY_UPDATED', 'HOLIDAY_DELETED',
    'CSV_IMPORTED', 'CSV_EXPORTED',
    'PENALTY_APPLIED', 'PENALTY_CLEARED',
    'SHIFT_ASSIGNED', 'DATA_RESET'
  ));

-- Add new columns to attendance_events for audit context
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'attendance_events' AND column_name = 'performed_by'
  ) THEN
    ALTER TABLE public.attendance_events ADD COLUMN performed_by text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'attendance_events' AND column_name = 'description'
  ) THEN
    ALTER TABLE public.attendance_events ADD COLUMN description text;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'attendance_events' AND column_name = 'metadata'
  ) THEN
    ALTER TABLE public.attendance_events ADD COLUMN metadata jsonb;
  END IF;
END $$;

-- Add timestamps to attendance_logs if missing
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'attendance_logs' AND column_name = 'created_at'
  ) THEN
    ALTER TABLE public.attendance_logs ADD COLUMN created_at timestamptz NOT NULL DEFAULT now();
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'attendance_logs' AND column_name = 'updated_at'
  ) THEN
    ALTER TABLE public.attendance_logs ADD COLUMN updated_at timestamptz NOT NULL DEFAULT now();
  END IF;
END $$;


-- ----------------------------------------------------------------------------
-- SOURCE: 044_notification_logs_add_read.sql
-- ----------------------------------------------------------------------------
-- Migration 044: Add read tracking columns to notification_logs
-- These columns track whether an in-app notification has been read by the recipient.

ALTER TABLE public.notification_logs
  ADD COLUMN IF NOT EXISTS read boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS read_at timestamp with time zone;

-- Index for fast unread queries per employee
CREATE INDEX IF NOT EXISTS idx_notif_unread ON public.notification_logs(employee_id, read)
  WHERE read = false;

-- Also add a link column for navigation (stores path without role prefix)
ALTER TABLE public.notification_logs
  ADD COLUMN IF NOT EXISTS link text;

-- Allow employees to update their own notification read status via RLS
DROP POLICY IF EXISTS nl_update_own ON public.notification_logs;
CREATE POLICY nl_update_own ON public.notification_logs
  FOR UPDATE USING (
    employee_id IN (
      SELECT id FROM public.employees WHERE profile_id = auth.uid()
    )
  )
  WITH CHECK (
    employee_id IN (
      SELECT id FROM public.employees WHERE profile_id = auth.uid()
    )
  );


-- ----------------------------------------------------------------------------
-- SOURCE: 047_push_subscriptions.sql
-- ----------------------------------------------------------------------------
-- Migration 047: Push Notification Subscriptions
--
-- Stores Web Push API subscriptions for PWA push notifications.
-- Each employee can have multiple subscriptions (different devices/browsers).

CREATE TABLE IF NOT EXISTS public.push_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  employee_id text NOT NULL,
  endpoint text NOT NULL,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_used_at timestamp with time zone,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT push_subscriptions_endpoint_key UNIQUE (endpoint),
  CONSTRAINT fk_push_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE
);

-- Index for fast lookups by employee
CREATE INDEX IF NOT EXISTS idx_push_subs_employee ON public.push_subscriptions(employee_id) WHERE is_active = true;

-- Index for endpoint lookups (for subscription management)
CREATE INDEX IF NOT EXISTS idx_push_subs_endpoint ON public.push_subscriptions(endpoint);

-- Enable RLS
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Employees can manage their own subscriptions
CREATE POLICY "Employees manage own push subscriptions"
  ON public.push_subscriptions
  FOR ALL
  USING (
    employee_id IN (
      SELECT e.id FROM public.employees e
      WHERE e.profile_id = auth.uid()
    )
  )
  WITH CHECK (
    employee_id IN (
      SELECT e.id FROM public.employees e
      WHERE e.profile_id = auth.uid()
    )
  );

-- Admin/HR can view all subscriptions (for debugging/support)
CREATE POLICY "Admin can view all push subscriptions"
  ON public.push_subscriptions
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE e.profile_id = auth.uid()
      AND e.role IN ('admin', 'hr')
    )
  );

-- Enable Realtime for push_subscriptions
ALTER TABLE public.push_subscriptions REPLICA IDENTITY FULL;
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.push_subscriptions;
EXCEPTION WHEN duplicate_object THEN NULL;
END;
$$;

COMMENT ON TABLE public.push_subscriptions IS 'Web Push API subscriptions for PWA push notifications';
COMMENT ON COLUMN public.push_subscriptions.endpoint IS 'Push service endpoint URL (unique per browser/device)';
COMMENT ON COLUMN public.push_subscriptions.p256dh IS 'Public key for encryption (base64url encoded)';
COMMENT ON COLUMN public.push_subscriptions.auth IS 'Authentication secret (base64url encoded)';


-- ----------------------------------------------------------------------------
-- SOURCE: 052_notification_provider_config.sql
-- ----------------------------------------------------------------------------
-- ─── Notification provider configuration singleton ─────────────────────────
-- Stores SMS/email provider settings (one row with id = 'default')

CREATE TABLE IF NOT EXISTS public.notification_provider_config (
  id text NOT NULL DEFAULT 'default'::text,
  sms_provider text NOT NULL DEFAULT 'simulated'::text,
  email_provider text NOT NULL DEFAULT 'simulated'::text,
  sms_enabled boolean NOT NULL DEFAULT true,
  email_enabled boolean NOT NULL DEFAULT true,
  default_sender_name text NOT NULL DEFAULT 'Premium Outlets'::text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notification_provider_config_pkey PRIMARY KEY (id)
);

-- Seed default row
INSERT INTO public.notification_provider_config (id) VALUES ('default') ON CONFLICT DO NOTHING;

-- RLS
ALTER TABLE public.notification_provider_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can read notification provider config"
  ON public.notification_provider_config FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins can update notification provider config"
  ON public.notification_provider_config FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Admins can insert notification provider config"
  ON public.notification_provider_config FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- ─── Seed default notification rules if table is empty ─────────────────────
-- The notification_rules table already exists; ensure it has the default rows.
INSERT INTO public.notification_rules (id, trigger, enabled, channel, recipient_roles, timing, schedule_time, reminder_days, subject_template, body_template, sms_template) VALUES
  ('NR-01', 'payslip_published', true, 'both', '{employee}', 'immediate', NULL, NULL, 'Payslip Ready: {period}', 'Hi {name}, your payslip for {period} is ready. Net pay: {amount}. Please sign in to Premium Outlets HRIS.', 'Your payslip for {period} is ready. Net: {amount}.'),
  ('NR-02', 'leave_submitted', true, 'email', '{admin,hr}', 'immediate', NULL, NULL, 'Leave Request: {name}', '{name} submitted a {leaveType} leave request ({dates}).', NULL),
  ('NR-03', 'leave_approved', true, 'both', '{employee}', 'immediate', NULL, NULL, 'Leave {status}: {dates}', 'Hi {name}, your {leaveType} leave ({dates}) has been {status}.', 'Your {leaveType} leave ({dates}) has been {status}.'),
  ('NR-04', 'leave_rejected', true, 'both', '{employee}', 'immediate', NULL, NULL, 'Leave Rejected: {dates}', 'Hi {name}, your {leaveType} leave ({dates}) has been rejected.', NULL),
  ('NR-05', 'attendance_missing', true, 'sms', '{employee}', 'scheduled', '10:00', NULL, 'Check-In Reminder', 'Reminder: You have not checked in today. Please check in.', 'Reminder: You have not checked in today.'),
  ('NR-06', 'geofence_violation', true, 'email', '{admin}', 'immediate', NULL, NULL, 'Geofence Violation: {name}', '{name} is outside the geofence at {time}. Distance: {distance}m.', NULL),
  ('NR-07', 'loan_reminder', true, 'sms', '{employee}', 'scheduled', NULL, '{3}', 'Loan Deduction Reminder', 'Reminder: {amount} loan deduction will be applied to your next payslip.', 'Reminder: {amount} loan deduction on next payslip.'),
  ('NR-08', 'payslip_unsigned_reminder', true, 'both', '{employee}', 'scheduled', NULL, '{1,3,5}', 'Sign Your Payslip: {period}', 'Reminder: Please sign your payslip for {period}.', 'Reminder: Sign your payslip for {period}.'),
  ('NR-09', 'overtime_submitted', true, 'email', '{admin,supervisor}', 'immediate', NULL, NULL, 'Overtime Request: {name}', '{name} submitted an overtime request for {date}.', NULL),
  ('NR-10', 'birthday', true, 'both', '{employee}', 'scheduled', '08:00', NULL, 'Happy Birthday!', 'Happy Birthday, {name}! Wishing you a great day!', 'Happy Birthday, {name}!'),
  ('NR-11', 'contract_expiry', true, 'email', '{admin,hr}', 'scheduled', NULL, '{30,7}', 'Contract Expiry: {name}', '{name}''s probation/contract ends on {date}. Action required.', NULL),
  ('NR-12', 'daily_summary', false, 'email', '{admin}', 'scheduled', '18:00', NULL, 'Daily Attendance Summary', 'Today: {present} present, {absent} absent, {onLeave} on leave.', NULL),
  ('NR-13', 'location_disabled', true, 'both', '{admin}', 'immediate', NULL, NULL, 'Location Disabled: {name}', '{name} has disabled location tracking at {time}.', '{name} disabled GPS at {time}.'),
  ('NR-14', 'payslip_signed', true, 'email', '{admin,finance}', 'immediate', NULL, NULL, 'Payslip Signed: {name} ({period})', '{name} has signed their payslip for {period}.', NULL),
  ('NR-15', 'payment_confirmed', true, 'sms', '{employee}', 'immediate', NULL, NULL, 'Payment Confirmed: {period}', 'Your payment for {period} has been confirmed. Amount: {amount}.', 'Payment confirmed for {period}. Amount: {amount}.')
ON CONFLICT (id) DO NOTHING;

