-- ============================================================================
-- 10_government_compliance.sql
-- ----------------------------------------------------------------------------
-- Consolidated from legacy migrations: 056, 057, 058
-- Apply order: run this file in the same numeric order as the file name.
-- Generated by scripts/build-migrations-v2.ps1 â€” DO NOT EDIT BY HAND.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SOURCE: 056_bir_compliance_foundation.sql
-- ----------------------------------------------------------------------------
-- =====================================================
-- Migration 056: BIR Compliance Engine Foundation
-- =====================================================
-- Adds the database foundation for the NexHRMS BIR Compliance Engine
-- per bir_alphalist.md plan:
--
--   1. Adds BIR-specific columns to employees & payslips
--   2. Creates 5 new tables:
--      - employee_tax_profiles
--      - annual_tax_summaries
--      - previous_employer_records
--      - form_2316_records
--      - alphalist_exports
--   3. Adds RLS policies (employees see own; payroll/finance/admin manage all)
--
-- Style: 100% additive, idempotent (IF NOT EXISTS), reversible-safe.
-- =====================================================

BEGIN;

-- ──────────────────────────────────────────────────────
-- STEP 0: Pre-flight
-- ──────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='employees') THEN
    RAISE EXCEPTION '[056] ABORTED: public.employees missing. Run migration 002 first.';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='payslips') THEN
    RAISE EXCEPTION '[056] ABORTED: public.payslips missing. Run migration 006 first.';
  END IF;
END $$;

-- ──────────────────────────────────────────────────────
-- STEP 1: Extend employees table with BIR fields
-- ──────────────────────────────────────────────────────
ALTER TABLE public.employees
  ADD COLUMN IF NOT EXISTS tin                       text,
  ADD COLUMN IF NOT EXISTS employment_classification text NOT NULL DEFAULT 'R'
    CHECK (employment_classification IN ('R','C','CP','S','P','AL')),
  ADD COLUMN IF NOT EXISTS is_mwe                    boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS mwe_daily_rate            numeric CHECK (mwe_daily_rate IS NULL OR mwe_daily_rate >= 0),
  ADD COLUMN IF NOT EXISTS substituted_filing        boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS tax_status                text NOT NULL DEFAULT 'S'
    CHECK (tax_status IN ('S','M','ME','MX')),
  ADD COLUMN IF NOT EXISTS tax_residency             text NOT NULL DEFAULT 'resident'
    CHECK (tax_residency IN ('resident','non_resident')),
  ADD COLUMN IF NOT EXISTS separation_date           date,
  ADD COLUMN IF NOT EXISTS separation_type           text
    CHECK (separation_type IS NULL OR separation_type IN ('resigned','terminated','end_of_contract'));

-- Unique TIN (only when set)
CREATE UNIQUE INDEX IF NOT EXISTS idx_employees_tin_unique
  ON public.employees(tin) WHERE tin IS NOT NULL;

COMMENT ON COLUMN public.employees.tin                       IS 'BIR Taxpayer Identification Number (12 digits NNN-NNN-NNN-NNN)';
COMMENT ON COLUMN public.employees.employment_classification IS 'BIR classification: R=Regular, C=Casual, CP=Contractual/Project, S=Seasonal, P=Probationary, AL=Apprentices/Learners';
COMMENT ON COLUMN public.employees.is_mwe                    IS 'Minimum Wage Earner flag — exempts basic, OT, holiday, night-diff, hazard pay from withholding';
COMMENT ON COLUMN public.employees.mwe_daily_rate            IS 'Region-specific MWE daily rate (used to validate MWE classification)';
COMMENT ON COLUMN public.employees.substituted_filing        IS 'True when employer files BIR return on employee behalf (Form 2316 in lieu of 1700)';
COMMENT ON COLUMN public.employees.tax_status                IS 'BIR tax status: S=Single, M=Married, ME=Married w/ Employed Spouse, MX=Married w/ Multiple Exemptions';
COMMENT ON COLUMN public.employees.tax_residency             IS 'Tax residency: resident or non_resident alien';

-- ──────────────────────────────────────────────────────
-- STEP 2: Extend payslips table with BIR category breakdown
-- ──────────────────────────────────────────────────────
ALTER TABLE public.payslips
  ADD COLUMN IF NOT EXISTS tax_categories            jsonb,
  ADD COLUMN IF NOT EXISTS taxable_compensation      numeric NOT NULL DEFAULT 0 CHECK (taxable_compensation     >= 0),
  ADD COLUMN IF NOT EXISTS non_taxable_compensation  numeric NOT NULL DEFAULT 0 CHECK (non_taxable_compensation >= 0);

COMMENT ON COLUMN public.payslips.tax_categories           IS 'BIR earnings breakdown (TaxCategoryBreakdown JSON)';
COMMENT ON COLUMN public.payslips.taxable_compensation     IS 'Total taxable compensation in this payslip period';
COMMENT ON COLUMN public.payslips.non_taxable_compensation IS 'Total non-taxable compensation (de minimis + MWE exempt + government contributions + 13th month within ceiling)';

-- ──────────────────────────────────────────────────────
-- STEP 3: employee_tax_profiles
-- ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employee_tax_profiles (
  id                        text NOT NULL DEFAULT ('ETP-' || gen_random_uuid()::text),
  employee_id               text NOT NULL,
  tin                       text,
  employment_classification text NOT NULL DEFAULT 'R'
    CHECK (employment_classification IN ('R','C','CP','S','P','AL')),
  is_mwe                    boolean NOT NULL DEFAULT false,
  mwe_daily_rate            numeric CHECK (mwe_daily_rate IS NULL OR mwe_daily_rate >= 0),
  substituted_filing        boolean NOT NULL DEFAULT false,
  tax_status                text NOT NULL DEFAULT 'S' CHECK (tax_status IN ('S','M','ME','MX')),
  tax_residency             text NOT NULL DEFAULT 'resident' CHECK (tax_residency IN ('resident','non_resident')),
  prev_employer_tin         text,
  prev_employer_name        text,
  prev_income               numeric CHECK (prev_income IS NULL OR prev_income >= 0),
  prev_tax_withheld         numeric CHECK (prev_tax_withheld IS NULL OR prev_tax_withheld >= 0),
  prev_2316_received        boolean NOT NULL DEFAULT false,
  separation_date           date,
  separation_type           text CHECK (separation_type IS NULL OR separation_type IN ('resigned','terminated','end_of_contract')),
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT employee_tax_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT employee_tax_profiles_employee_unique UNIQUE (employee_id),
  CONSTRAINT employee_tax_profiles_employee_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_etp_employee ON public.employee_tax_profiles(employee_id);
CREATE INDEX IF NOT EXISTS idx_etp_tin      ON public.employee_tax_profiles(tin) WHERE tin IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_etp_mwe      ON public.employee_tax_profiles(is_mwe) WHERE is_mwe = true;

-- ──────────────────────────────────────────────────────
-- STEP 4: annual_tax_summaries
-- ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.annual_tax_summaries (
  id                       text NOT NULL DEFAULT ('ATS-' || gen_random_uuid()::text),
  employee_id              text NOT NULL,
  year                     integer NOT NULL CHECK (year BETWEEN 2000 AND 2100),
  total_taxable_comp       numeric NOT NULL DEFAULT 0 CHECK (total_taxable_comp >= 0),
  total_non_taxable_comp   numeric NOT NULL DEFAULT 0 CHECK (total_non_taxable_comp >= 0),
  total_de_minimis         numeric NOT NULL DEFAULT 0 CHECK (total_de_minimis >= 0),
  total_sss                numeric NOT NULL DEFAULT 0 CHECK (total_sss >= 0),
  total_philhealth         numeric NOT NULL DEFAULT 0 CHECK (total_philhealth >= 0),
  total_pagibig            numeric NOT NULL DEFAULT 0 CHECK (total_pagibig >= 0),
  total_13th_non_taxable   numeric NOT NULL DEFAULT 0 CHECK (total_13th_non_taxable >= 0),
  total_13th_taxable       numeric NOT NULL DEFAULT 0 CHECK (total_13th_taxable >= 0),
  total_other_benefits     numeric NOT NULL DEFAULT 0 CHECK (total_other_benefits >= 0),
  total_tax_withheld       numeric NOT NULL DEFAULT 0 CHECK (total_tax_withheld >= 0),
  prev_employer_income     numeric NOT NULL DEFAULT 0 CHECK (prev_employer_income >= 0),
  prev_employer_tax        numeric NOT NULL DEFAULT 0 CHECK (prev_employer_tax >= 0),
  annual_tax_due           numeric CHECK (annual_tax_due IS NULL OR annual_tax_due >= 0),
  adjustment_type          text CHECK (adjustment_type IS NULL OR adjustment_type IN ('over_withheld','under_withheld','balanced')),
  adjustment_amount        numeric,
  status                   text NOT NULL DEFAULT 'open'
    CHECK (status IN ('open','reconciled','finalized','exported')),
  finalized_at             timestamptz,
  finalized_by             text,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT annual_tax_summaries_pkey PRIMARY KEY (id),
  CONSTRAINT annual_tax_summaries_employee_year_unique UNIQUE (employee_id, year),
  CONSTRAINT annual_tax_summaries_employee_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_ats_employee_year ON public.annual_tax_summaries(employee_id, year);
CREATE INDEX IF NOT EXISTS idx_ats_year_status   ON public.annual_tax_summaries(year, status);

-- ──────────────────────────────────────────────────────
-- STEP 5: previous_employer_records
-- ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.previous_employer_records (
  id                  text NOT NULL DEFAULT ('PER-' || gen_random_uuid()::text),
  employee_id         text NOT NULL,
  year                integer NOT NULL CHECK (year BETWEEN 2000 AND 2100),
  employer_name       text NOT NULL,
  employer_tin        text,
  employer_address    text,
  total_income        numeric NOT NULL DEFAULT 0 CHECK (total_income >= 0),
  total_tax_withheld  numeric NOT NULL DEFAULT 0 CHECK (total_tax_withheld >= 0),
  reference_2316      text,
  submitted_at        timestamptz NOT NULL DEFAULT now(),
  submitted_by        text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT previous_employer_records_pkey PRIMARY KEY (id),
  CONSTRAINT previous_employer_records_employee_year_unique UNIQUE (employee_id, year),
  CONSTRAINT previous_employer_records_employee_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_per_employee_year ON public.previous_employer_records(employee_id, year);

-- ──────────────────────────────────────────────────────
-- STEP 6: form_2316_records
-- ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.form_2316_records (
  id                       text NOT NULL DEFAULT ('F2316-' || gen_random_uuid()::text),
  employee_id              text NOT NULL,
  year                     integer NOT NULL CHECK (year BETWEEN 2000 AND 2100),
  annual_summary_id        text,
  generated_at             timestamptz NOT NULL DEFAULT now(),
  generated_by             text,
  employer_signed_at       timestamptz,
  employer_signed_by       text,
  employer_signature_url   text,
  employee_signed_at       timestamptz,
  employee_signature_url   text,
  pdf_url                  text,
  document_hash            text,
  status                   text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft','for_signature','released','downloaded','revoked')),
  released_at              timestamptz,
  downloaded_at            timestamptz,
  downloaded_by            text,
  revoked_at               timestamptz,
  revoked_by               text,
  revoke_reason            text,
  created_at               timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT form_2316_records_pkey PRIMARY KEY (id),
  CONSTRAINT form_2316_records_employee_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE,
  CONSTRAINT form_2316_records_summary_fkey  FOREIGN KEY (annual_summary_id) REFERENCES public.annual_tax_summaries(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_f2316_employee_year ON public.form_2316_records(employee_id, year);
CREATE INDEX IF NOT EXISTS idx_f2316_status        ON public.form_2316_records(status);

-- ──────────────────────────────────────────────────────
-- STEP 7: alphalist_exports
-- ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.alphalist_exports (
  id                  text NOT NULL DEFAULT ('ALX-' || gen_random_uuid()::text),
  year                integer NOT NULL CHECK (year BETWEEN 2000 AND 2100),
  schedule_type       text NOT NULL CHECK (schedule_type IN ('schedule_1','schedule_2','both')),
  generated_at        timestamptz NOT NULL DEFAULT now(),
  generated_by        text,
  employee_count      integer NOT NULL DEFAULT 0 CHECK (employee_count >= 0),
  total_taxable_comp  numeric NOT NULL DEFAULT 0 CHECK (total_taxable_comp >= 0),
  total_tax_withheld  numeric NOT NULL DEFAULT 0 CHECK (total_tax_withheld >= 0),
  validation_status   text NOT NULL DEFAULT 'passed'
    CHECK (validation_status IN ('passed','has_warnings','has_errors')),
  validation_errors   jsonb,
  export_format       text NOT NULL CHECK (export_format IN ('csv','xlsx','dat')),
  file_url            text,
  efps_status         text NOT NULL DEFAULT 'draft'
    CHECK (efps_status IN ('draft','validated','ready','submitted','payment_pending','paid','completed')),
  submitted_at        timestamptz,
  submitted_by        text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT alphalist_exports_pkey PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_alx_year_schedule ON public.alphalist_exports(year, schedule_type);
CREATE INDEX IF NOT EXISTS idx_alx_efps_status   ON public.alphalist_exports(efps_status);

-- ──────────────────────────────────────────────────────
-- STEP 8: Row-Level Security
-- ──────────────────────────────────────────────────────
ALTER TABLE public.employee_tax_profiles    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.annual_tax_summaries     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.previous_employer_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.form_2316_records        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alphalist_exports        ENABLE ROW LEVEL SECURITY;

-- Helper macro: payroll/finance/admin role check
-- (inlined for clarity since CREATE POLICY can't reference a function from this DDL safely in all environments)

-- employee_tax_profiles
DROP POLICY IF EXISTS etp_employee_read_own  ON public.employee_tax_profiles;
DROP POLICY IF EXISTS etp_admin_manage_all   ON public.employee_tax_profiles;
CREATE POLICY etp_employee_read_own ON public.employee_tax_profiles
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.employees e
            WHERE e.id = employee_tax_profiles.employee_id AND e.profile_id = auth.uid())
  );
CREATE POLICY etp_admin_manage_all ON public.employee_tax_profiles
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.employees e
            WHERE e.profile_id = auth.uid()
              AND e.role IN ('admin','hr','finance','payroll_admin'))
  );

-- annual_tax_summaries
DROP POLICY IF EXISTS ats_employee_read_own ON public.annual_tax_summaries;
DROP POLICY IF EXISTS ats_admin_manage_all  ON public.annual_tax_summaries;
CREATE POLICY ats_employee_read_own ON public.annual_tax_summaries
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.employees e
            WHERE e.id = annual_tax_summaries.employee_id AND e.profile_id = auth.uid())
  );
CREATE POLICY ats_admin_manage_all ON public.annual_tax_summaries
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.employees e
            WHERE e.profile_id = auth.uid()
              AND e.role IN ('admin','finance','payroll_admin'))
  );

-- previous_employer_records
DROP POLICY IF EXISTS per_employee_read_own ON public.previous_employer_records;
DROP POLICY IF EXISTS per_admin_manage_all  ON public.previous_employer_records;
CREATE POLICY per_employee_read_own ON public.previous_employer_records
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.employees e
            WHERE e.id = previous_employer_records.employee_id AND e.profile_id = auth.uid())
  );
CREATE POLICY per_admin_manage_all ON public.previous_employer_records
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.employees e
            WHERE e.profile_id = auth.uid()
              AND e.role IN ('admin','hr','finance','payroll_admin'))
  );

-- form_2316_records
DROP POLICY IF EXISTS f2316_employee_read_own ON public.form_2316_records;
DROP POLICY IF EXISTS f2316_admin_manage_all  ON public.form_2316_records;
CREATE POLICY f2316_employee_read_own ON public.form_2316_records
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.employees e
            WHERE e.id = form_2316_records.employee_id AND e.profile_id = auth.uid())
      AND status IN ('released','downloaded')
  );
CREATE POLICY f2316_admin_manage_all ON public.form_2316_records
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.employees e
            WHERE e.profile_id = auth.uid()
              AND e.role IN ('admin','finance','payroll_admin'))
  );

-- alphalist_exports — admin only
DROP POLICY IF EXISTS alx_admin_manage_all ON public.alphalist_exports;
CREATE POLICY alx_admin_manage_all ON public.alphalist_exports
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.employees e
            WHERE e.profile_id = auth.uid()
              AND e.role IN ('admin','finance','payroll_admin'))
  );

COMMIT;

-- =====================================================
-- Migration 056 — done
-- =====================================================


-- ----------------------------------------------------------------------------
-- SOURCE: 057_employee_201_files_disciplinary.sql
-- ----------------------------------------------------------------------------
-- =====================================================
-- Migration 057: Employee 201 Files + Disciplinary (NTE / NOD)
-- =====================================================
-- Adds the database foundation for the Document Center / 201 File
-- module and the disciplinary workflow (NTE → NOD).
--
-- Style: 100% additive, idempotent (IF NOT EXISTS), reversible-safe.
-- Mirrors migration 056 (BIR foundation).
-- =====================================================

BEGIN;

-- ──────────────────────────────────────────────────────
-- STEP 0: Pre-flight
-- ──────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='employees') THEN
    RAISE EXCEPTION '[057] ABORTED: public.employees missing. Run migration 002 first.';
  END IF;
END $$;

-- ──────────────────────────────────────────────────────
-- STEP 1: 201 documents table (rich, replaces ad-hoc employee_documents)
-- ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.employee_201_documents (
  id              text PRIMARY KEY,
  employee_id     text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  document_type   text NOT NULL CHECK (document_type IN (
                    'personal_info','employment_contract','government_id',
                    'resume','application_form','job_offer','medical',
                    'training_certificate','performance_evaluation',
                    'payslip','leave_record','warning','nte','nod',
                    'clearance','resignation_letter','coe',
                    'final_pay_document','other')),
  document_title  text NOT NULL,
  file_path       text,
  file_type       text,
  file_size       bigint,
  status          text NOT NULL DEFAULT 'uploaded' CHECK (status IN (
                    'pending_upload','uploaded','for_review','approved',
                    'rejected','expired','archived')),
  visibility      text NOT NULL DEFAULT 'hr_only' CHECK (visibility IN (
                    'hr_only','manager','employee','payroll','admin_only')),
  expiry_date     date,
  remarks         text,
  uploaded_by     text,
  reviewed_by     text,
  reviewed_at     timestamptz,
  case_id         text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_201docs_employee ON public.employee_201_documents(employee_id);
CREATE INDEX IF NOT EXISTS idx_201docs_status   ON public.employee_201_documents(status);
CREATE INDEX IF NOT EXISTS idx_201docs_emp_type ON public.employee_201_documents(employee_id, document_type);
CREATE INDEX IF NOT EXISTS idx_201docs_expiry   ON public.employee_201_documents(expiry_date);

-- ──────────────────────────────────────────────────────
-- STEP 2: Disciplinary cases (parent of NTE/NOD)
-- ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.disciplinary_cases (
  id                 text PRIMARY KEY,
  case_number        text NOT NULL UNIQUE,
  employee_id        text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  violation_type     text NOT NULL,
  policy_reference   text,
  incident_date      timestamptz NOT NULL,
  incident_location  text,
  description        text NOT NULL,
  evidence_urls      jsonb NOT NULL DEFAULT '[]'::jsonb,
  status             text NOT NULL DEFAULT 'open' CHECK (status IN (
                       'open','nte_issued','nte_acknowledged','explanation_submitted',
                       'no_response','under_review','nod_issued','nod_acknowledged',
                       'sanction_active','closed')),
  assigned_hr        text,
  created_by         text NOT NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_disc_cases_employee ON public.disciplinary_cases(employee_id);
CREATE INDEX IF NOT EXISTS idx_disc_cases_status   ON public.disciplinary_cases(status);

-- ──────────────────────────────────────────────────────
-- STEP 3: NTE records (one per case)
-- ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.nte_records (
  id                       text PRIMARY KEY,
  case_id                  text NOT NULL UNIQUE
                             REFERENCES public.disciplinary_cases(id) ON DELETE CASCADE,
  employee_id              text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  response_deadline        date NOT NULL,
  document_id              text,
  issued_by                text NOT NULL,
  issued_at                timestamptz NOT NULL DEFAULT now(),
  acknowledged_at          timestamptz,
  employee_explanation     text,
  explanation_submitted_at timestamptz,
  status                   text NOT NULL DEFAULT 'issued' CHECK (status IN (
                             'draft','issued','acknowledged','explanation_submitted',
                             'no_response','under_review','closed','moved_to_nod')),
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_nte_employee ON public.nte_records(employee_id);
CREATE INDEX IF NOT EXISTS idx_nte_status   ON public.nte_records(status);

-- ──────────────────────────────────────────────────────
-- STEP 4: NOD records (one per case)
-- ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.nod_records (
  id                  text PRIMARY KEY,
  case_id             text NOT NULL UNIQUE
                        REFERENCES public.disciplinary_cases(id) ON DELETE CASCADE,
  employee_id         text NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
  decision            text NOT NULL CHECK (decision IN (
                        'no_violation','verbal_warning','written_warning',
                        'final_warning','suspension','termination',
                        'salary_deduction','training_required','pip')),
  sanction_start_date date,
  sanction_end_date   date,
  return_to_work_date date,
  decision_details    text NOT NULL,
  document_id         text,
  issued_by           text NOT NULL,
  issued_at           timestamptz NOT NULL DEFAULT now(),
  acknowledged_at     timestamptz,
  status              text NOT NULL DEFAULT 'issued' CHECK (status IN (
                        'draft','issued','acknowledged','sanction_active','completed','closed')),
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_nod_employee ON public.nod_records(employee_id);
CREATE INDEX IF NOT EXISTS idx_nod_status   ON public.nod_records(status);

-- ──────────────────────────────────────────────────────
-- STEP 5: updated_at triggers (reuse existing helper if present)
-- ──────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'set_updated_at') THEN
    CREATE OR REPLACE FUNCTION public.set_updated_at()
    RETURNS trigger AS $fn$
    BEGIN
      NEW.updated_at = now();
      RETURN NEW;
    END;
    $fn$ LANGUAGE plpgsql;
  END IF;
END $$;

DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT unnest(ARRAY['employee_201_documents','disciplinary_cases','nte_records','nod_records']) LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS trg_%I_updated_at ON public.%I;', t, t);
    EXECUTE format('CREATE TRIGGER trg_%I_updated_at BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();', t, t);
  END LOOP;
END $$;

-- ──────────────────────────────────────────────────────
-- STEP 6: Enable RLS
-- ──────────────────────────────────────────────────────
ALTER TABLE public.employee_201_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.disciplinary_cases     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nte_records            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nod_records            ENABLE ROW LEVEL SECURITY;

-- Helper: lookup current employee role from auth.uid()
-- Reuses the same pattern as migration 056.

-- ── employee_201_documents policies ──────────────────────────
DROP POLICY IF EXISTS "201docs hr full" ON public.employee_201_documents;
CREATE POLICY "201docs hr full" ON public.employee_201_documents
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin','hr')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin','hr')
    )
  );

DROP POLICY IF EXISTS "201docs employee read own" ON public.employee_201_documents;
CREATE POLICY "201docs employee read own" ON public.employee_201_documents
  FOR SELECT TO authenticated
  USING (
    visibility = 'employee'
    AND EXISTS (
      SELECT 1 FROM public.employees e
      WHERE e.id = employee_201_documents.employee_id
        AND (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
    )
  );

DROP POLICY IF EXISTS "201docs payroll read" ON public.employee_201_documents;
CREATE POLICY "201docs payroll read" ON public.employee_201_documents
  FOR SELECT TO authenticated
  USING (
    visibility IN ('payroll','hr_only')
    AND EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('finance','payroll_admin')
    )
  );

-- ── disciplinary_cases policies ─────────────────────────────
DROP POLICY IF EXISTS "disc cases hr full" ON public.disciplinary_cases;
CREATE POLICY "disc cases hr full" ON public.disciplinary_cases
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin','hr')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin','hr')
    )
  );

DROP POLICY IF EXISTS "disc cases employee read own" ON public.disciplinary_cases;
CREATE POLICY "disc cases employee read own" ON public.disciplinary_cases
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE e.id = disciplinary_cases.employee_id
        AND (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
    )
  );

-- ── nte_records policies ────────────────────────────────────
DROP POLICY IF EXISTS "nte hr full" ON public.nte_records;
CREATE POLICY "nte hr full" ON public.nte_records
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin','hr')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin','hr')
    )
  );

DROP POLICY IF EXISTS "nte employee select own" ON public.nte_records;
CREATE POLICY "nte employee select own" ON public.nte_records
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE e.id = nte_records.employee_id
        AND (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
    )
  );

DROP POLICY IF EXISTS "nte employee submit own" ON public.nte_records;
CREATE POLICY "nte employee submit own" ON public.nte_records
  FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE e.id = nte_records.employee_id
        AND (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE e.id = nte_records.employee_id
        AND (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
    )
  );

-- ── nod_records policies ────────────────────────────────────
DROP POLICY IF EXISTS "nod hr full" ON public.nod_records;
CREATE POLICY "nod hr full" ON public.nod_records
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin','hr')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin','hr')
    )
  );

DROP POLICY IF EXISTS "nod employee select own" ON public.nod_records;
CREATE POLICY "nod employee select own" ON public.nod_records
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE e.id = nod_records.employee_id
        AND (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
    )
  );

DROP POLICY IF EXISTS "nod employee ack own" ON public.nod_records;
CREATE POLICY "nod employee ack own" ON public.nod_records
  FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE e.id = nod_records.employee_id
        AND (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE e.id = nod_records.employee_id
        AND (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
    )
  );

-- ──────────────────────────────────────────────────────
-- STEP 7: Storage bucket for 201 docs (private)
-- ──────────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'employee-documents',
  'employee-documents',
  false,
  26214400,  -- 25 MB
  ARRAY[
    'application/pdf',
    'image/jpeg','image/png',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/msword'
  ]
)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "201 storage hr write" ON storage.objects;
CREATE POLICY "201 storage hr write" ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'employee-documents'
    AND EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin','hr')
    )
  )
  WITH CHECK (
    bucket_id = 'employee-documents'
    AND EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin','hr')
    )
  );

DROP POLICY IF EXISTS "201 storage employee read own" ON storage.objects;
CREATE POLICY "201 storage employee read own" ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'employee-documents'
    -- folder convention: <employee_id>/<filename>
    AND EXISTS (
      SELECT 1 FROM public.employees e
      WHERE e.id = (storage.foldername(name))[1]
        AND (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
    )
  );

COMMIT;

-- =====================================================
-- Migration 057 complete.
-- =====================================================


-- ----------------------------------------------------------------------------
-- SOURCE: 058_jobs.sql
-- ----------------------------------------------------------------------------
-- =====================================================
-- Migration 058: Jobs / Talent Acquisition
-- =====================================================
-- Adds the database foundation for the Jobs module:
--   • job_postings  — open positions managed by HR / admin
--   • job_applications — applicant pipeline per posting
--
-- Style: 100% additive, idempotent (IF NOT EXISTS), reversible-safe.
-- Mirrors migration 057 style.
-- =====================================================

BEGIN;

-- ──────────────────────────────────────────────────────
-- STEP 0: Pre-flight
-- ──────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'employees'
  ) THEN
    RAISE EXCEPTION '[058] ABORTED: public.employees missing. Run migration 002 first.';
  END IF;
END $$;

-- ──────────────────────────────────────────────────────
-- STEP 1: job_postings
-- ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_postings (
  id               text PRIMARY KEY,
  title            text NOT NULL,
  department       text NOT NULL,
  location         text NOT NULL,
  type             text NOT NULL CHECK (type IN (
                     'full_time','part_time','contract','internship','freelance')),
  status           text NOT NULL DEFAULT 'open' CHECK (status IN (
                     'draft','open','on_hold','closed')),
  priority         text NOT NULL DEFAULT 'medium' CHECK (priority IN (
                     'low','medium','high','urgent')),
  headcount        integer NOT NULL DEFAULT 1 CHECK (headcount >= 1),
  salary_min       numeric(12,2),
  salary_max       numeric(12,2),
  description      text NOT NULL DEFAULT '',
  requirements     text NOT NULL DEFAULT '',
  responsibilities text NOT NULL DEFAULT '',
  deadline         date,
  created_by       text NOT NULL,               -- employee id
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),

  -- integrity: salary_min <= salary_max when both are set
  CONSTRAINT job_salary_range_check CHECK (
    salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max
  )
);

CREATE INDEX IF NOT EXISTS idx_job_postings_status     ON public.job_postings(status);
CREATE INDEX IF NOT EXISTS idx_job_postings_department ON public.job_postings(department);
CREATE INDEX IF NOT EXISTS idx_job_postings_created_at ON public.job_postings(created_at DESC);

-- ──────────────────────────────────────────────────────
-- STEP 2: job_applications
-- ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.job_applications (
  id                text PRIMARY KEY,
  job_id            text NOT NULL REFERENCES public.job_postings(id) ON DELETE CASCADE,
  applicant_name    text NOT NULL,
  applicant_email   text NOT NULL,
  applicant_phone   text,
  resume_url        text,
  cover_letter      text,
  source            text NOT NULL DEFAULT 'Other',
  status            text NOT NULL DEFAULT 'applied' CHECK (status IN (
                      'applied','screening','interview','offer','hired','rejected','withdrawn')),
  interview_date    timestamptz,
  offer_salary      numeric(12,2),
  notes             text,
  reviewed_by          text,                       -- employee id
  reviewed_at          timestamptz,
  -- file stored in Supabase Storage bucket "job-resumes"
  resume_storage_path  text,                       -- storage object path (private)
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_job_apps_job_id     ON public.job_applications(job_id);
CREATE INDEX IF NOT EXISTS idx_job_apps_status     ON public.job_applications(status);
CREATE INDEX IF NOT EXISTS idx_job_apps_email      ON public.job_applications(applicant_email);
CREATE INDEX IF NOT EXISTS idx_job_apps_created_at ON public.job_applications(created_at DESC);

-- ──────────────────────────────────────────────────────
-- STEP 3: updated_at triggers (reuse existing helper)
-- ──────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'set_updated_at') THEN
    CREATE OR REPLACE FUNCTION public.set_updated_at()
    RETURNS trigger AS $fn$
    BEGIN
      NEW.updated_at = now();
      RETURN NEW;
    END;
    $fn$ LANGUAGE plpgsql;
  END IF;
END $$;

DO $$
DECLARE t text;
BEGIN
  FOR t IN SELECT unnest(ARRAY['job_postings','job_applications']) LOOP
    EXECUTE format(
      'DROP TRIGGER IF EXISTS trg_%I_updated_at ON public.%I;', t, t
    );
    EXECUTE format(
      'CREATE TRIGGER trg_%I_updated_at
       BEFORE UPDATE ON public.%I
       FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();',
      t, t
    );
  END LOOP;
END $$;

-- ──────────────────────────────────────────────────────
-- STEP 4: Row Level Security
-- ──────────────────────────────────────────────────────
ALTER TABLE public.job_postings     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.job_applications ENABLE ROW LEVEL SECURITY;

-- Helper inline CTE:
--   Checks that the authenticated user maps to an employee with role admin or hr.

-- ── job_postings policies ────────────────────────────────────────────────────

DROP POLICY IF EXISTS "jobs hr full" ON public.job_postings;
CREATE POLICY "jobs hr full" ON public.job_postings
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin', 'hr')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin', 'hr')
    )
  );

-- Employees can read open postings (for self-service / internal job board)
DROP POLICY IF EXISTS "jobs employee read open" ON public.job_postings;
CREATE POLICY "jobs employee read open" ON public.job_postings
  FOR SELECT TO authenticated
  USING (
    status = 'open'
    AND EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
    )
  );

-- ── job_applications policies ────────────────────────────────────────────────

DROP POLICY IF EXISTS "job apps hr full" ON public.job_applications;
CREATE POLICY "job apps hr full" ON public.job_applications
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin', 'hr')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin', 'hr')
    )
  );

-- ──────────────────────────────────────────────────────
-- STEP 5: Stats view (optional — convenient for dashboards)
-- ──────────────────────────────────────────────────────
CREATE OR REPLACE VIEW public.job_stats AS
SELECT
  COUNT(*) FILTER (WHERE status = 'open')    AS open_postings,
  COUNT(*) FILTER (WHERE status = 'draft')   AS draft_postings,
  COUNT(*) FILTER (WHERE status = 'on_hold') AS on_hold_postings,
  COUNT(*) FILTER (WHERE status = 'closed')  AS closed_postings,
  COUNT(*)                                   AS total_postings
FROM public.job_postings;

CREATE OR REPLACE VIEW public.job_pipeline_stats AS
SELECT
  jp.id            AS job_id,
  jp.title,
  jp.department,
  jp.status,
  COUNT(ja.id)                                                  AS total_applicants,
  COUNT(ja.id) FILTER (WHERE ja.status = 'applied')            AS applied,
  COUNT(ja.id) FILTER (WHERE ja.status = 'screening')          AS screening,
  COUNT(ja.id) FILTER (WHERE ja.status = 'interview')          AS interview,
  COUNT(ja.id) FILTER (WHERE ja.status = 'offer')              AS offer,
  COUNT(ja.id) FILTER (WHERE ja.status = 'hired')              AS hired,
  COUNT(ja.id) FILTER (WHERE ja.status = 'rejected')           AS rejected,
  COUNT(ja.id) FILTER (WHERE ja.status = 'withdrawn')          AS withdrawn
FROM public.job_postings jp
LEFT JOIN public.job_applications ja ON ja.job_id = jp.id
GROUP BY jp.id, jp.title, jp.department, jp.status;

-- ──────────────────────────────────────────────────────
-- STEP 5: Private storage bucket for applicant resumes
-- ──────────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'job-resumes',
  'job-resumes',
  false,
  10485760,  -- 10 MB
  ARRAY[
    'application/pdf',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
  ]
)
ON CONFLICT (id) DO NOTHING;

-- HR / admin: full read + write access to all resumes
DROP POLICY IF EXISTS "job resumes hr write" ON storage.objects;
CREATE POLICY "job resumes hr write" ON storage.objects
  FOR ALL TO authenticated
  USING (
    bucket_id = 'job-resumes'
    AND EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin', 'hr')
    )
  )
  WITH CHECK (
    bucket_id = 'job-resumes'
    AND EXISTS (
      SELECT 1 FROM public.employees e
      WHERE (e.profile_id = auth.uid() OR e.email = (auth.jwt() ->> 'email'))
        AND e.role IN ('admin', 'hr')
    )
  );

COMMIT;

-- =====================================================
-- Migration 058 complete.
-- =====================================================
-- 
-- Useful queries after running this migration:
--
-- 1. List all open postings with applicant counts:
--    SELECT * FROM public.job_pipeline_stats WHERE status = 'open';
--
-- 2. Get overall stats:
--    SELECT * FROM public.job_stats;
--
-- 3. Applicant pipeline for a specific job:
--    SELECT * FROM public.job_applications
--    WHERE job_id = '<id>'
--    ORDER BY created_at DESC;
--
-- 4. Hired applicants this month:
--    SELECT ja.*, jp.title
--    FROM public.job_applications ja
--    JOIN public.job_postings jp ON jp.id = ja.job_id
--    WHERE ja.status = 'hired'
--      AND ja.updated_at >= date_trunc('month', now());
--
-- 5. All applicants with uploaded resumes:
--    SELECT id, applicant_name, applicant_email, resume_storage_path
--    FROM public.job_applications
--    WHERE resume_storage_path IS NOT NULL
--    ORDER BY created_at DESC;
--
-- 6. Full pipeline for a job (use the view):
--    SELECT * FROM public.job_pipeline_stats WHERE job_id = '<id>';
--
-- NOTE: Resume download URLs are signed (private bucket).
--   Generate in your app via supabase.storage.from('job-resumes').createSignedUrl(path, 3600)
-- =====================================================

