-- ============================================================================
-- 11_storage_buckets.sql
-- ----------------------------------------------------------------------------
-- Consolidated from legacy migrations: 050
-- Apply order: run this file in the same numeric order as the file name.
-- Generated by scripts/build-migrations-v2.ps1 â€” DO NOT EDIT BY HAND.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SOURCE: 050_avatars_storage_bucket.sql
-- ----------------------------------------------------------------------------
-- Create avatars storage bucket for employee profile pictures
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'avatars',
  'avatars',
  true,
  5242880, -- 5MB
  ARRAY['image/jpeg', 'image/png', 'image/gif', 'image/webp']
)
ON CONFLICT (id) DO NOTHING;

-- Allow authenticated users to upload their own avatar
CREATE POLICY "Users can upload their own avatar"
  ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (bucket_id = 'avatars');

-- Allow public read access to avatars
CREATE POLICY "Avatars are publicly readable"
  ON storage.objects FOR SELECT
  TO public
  USING (bucket_id = 'avatars');

-- Allow authenticated users to update/delete their own avatars
CREATE POLICY "Users can update their own avatar"
  ON storage.objects FOR UPDATE
  TO authenticated
  USING (bucket_id = 'avatars');

CREATE POLICY "Users can delete their own avatar"
  ON storage.objects FOR DELETE
  TO authenticated
  USING (bucket_id = 'avatars');

