-- ============================================================================
-- 14_constraints_and_indexes.sql
-- ----------------------------------------------------------------------------
-- Consolidated from legacy migrations: 014, 015
-- Apply order: run this file in the same numeric order as the file name.
-- Generated by scripts/build-migrations-v2.ps1 â€” DO NOT EDIT BY HAND.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- SOURCE: 014_add_missing_fk_constraints.sql
-- ----------------------------------------------------------------------------
-- ════════════════════════════════════════════════════════════════════
-- 014: Add missing foreign key constraints
-- Idempotent: uses DO blocks to check before adding
-- ════════════════════════════════════════════════════════════════════

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pings_employee') THEN
  ALTER TABLE public.location_pings
    ADD CONSTRAINT fk_pings_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_breaks_employee') THEN
  ALTER TABLE public.break_records
    ADD CONSTRAINT fk_breaks_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ssp_employee') THEN
  ALTER TABLE public.site_survey_photos
    ADD CONSTRAINT fk_ssp_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tcr_employee') THEN
  ALTER TABLE public.task_completion_reports
    ADD CONSTRAINT fk_tcr_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tc_employee') THEN
  ALTER TABLE public.task_comments
    ADD CONSTRAINT fk_tc_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_cm_employee') THEN
  ALTER TABLE public.channel_messages
    ADD CONSTRAINT fk_cm_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_nl_employee') THEN
  ALTER TABLE public.notification_logs
    ADD CONSTRAINT fk_nl_employee FOREIGN KEY (employee_id) REFERENCES public.employees(id) ON DELETE CASCADE;
END IF;
END $$;

-- ═══ Project ID references (SET NULL on delete) ═══

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ae_project') THEN
  ALTER TABLE public.attendance_events
    ADD CONSTRAINT fk_ae_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_al_project') THEN
  ALTER TABLE public.attendance_logs
    ADD CONSTRAINT fk_al_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ot_project') THEN
  ALTER TABLE public.overtime_requests
    ADD CONSTRAINT fk_ot_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_kd_project') THEN
  ALTER TABLE public.kiosk_devices
    ADD CONSTRAINT fk_kd_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_tg_project') THEN
  ALTER TABLE public.task_groups
    ADD CONSTRAINT fk_tg_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;
END IF;
END $$;

-- ═══ Deferred FKs: attendance tables → projects / kiosk_devices ═══

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pvm_project') THEN
  ALTER TABLE public.project_verification_methods
    ADD CONSTRAINT fk_pvm_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_mci_project') THEN
  ALTER TABLE public.manual_checkins
    ADD CONSTRAINT fk_mci_project FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE SET NULL;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_qrt_device') THEN
  ALTER TABLE public.qr_tokens
    ADD CONSTRAINT fk_qrt_device FOREIGN KEY (device_id) REFERENCES public.kiosk_devices(id) ON DELETE CASCADE;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_kp_device') THEN
  ALTER TABLE public.kiosk_pins
    ADD CONSTRAINT fk_kp_device FOREIGN KEY (kiosk_device_id) REFERENCES public.kiosk_devices(id) ON DELETE CASCADE;
END IF;
END $$;

-- ═══ Payslip references (SET NULL on delete) ═══

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_ld_payslip') THEN
  ALTER TABLE public.loan_deductions
    ADD CONSTRAINT fk_ld_payslip FOREIGN KEY (payslip_id) REFERENCES public.payslips(id) ON DELETE SET NULL;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lrs_payslip') THEN
  ALTER TABLE public.loan_repayment_schedule
    ADD CONSTRAINT fk_lrs_payslip FOREIGN KEY (payslip_id) REFERENCES public.payslips(id) ON DELETE SET NULL;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_lbh_payslip') THEN
  ALTER TABLE public.loan_balance_history
    ADD CONSTRAINT fk_lbh_payslip FOREIGN KEY (payslip_id) REFERENCES public.payslips(id) ON DELETE SET NULL;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_fpc_payslip') THEN
  ALTER TABLE public.final_pay_computations
    ADD CONSTRAINT fk_fpc_payslip FOREIGN KEY (payslip_id) REFERENCES public.payslips(id) ON DELETE SET NULL;
END IF;
END $$;

-- ═══ Payroll run references ═══

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pa_run') THEN
  ALTER TABLE public.payroll_adjustments
    ADD CONSTRAINT fk_pa_run FOREIGN KEY (payroll_run_id) REFERENCES public.payroll_runs(id) ON DELETE CASCADE;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_pa_payslip') THEN
  ALTER TABLE public.payroll_adjustments
    ADD CONSTRAINT fk_pa_payslip FOREIGN KEY (reference_payslip_id) REFERENCES public.payslips(id) ON DELETE CASCADE;
END IF;
END $$;

-- ═══ Shift/Employee references ═══

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_emp_shift') THEN
  ALTER TABLE public.employees
    ADD CONSTRAINT fk_emp_shift FOREIGN KEY (shift_id) REFERENCES public.shift_templates(id) ON DELETE SET NULL;
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_al_shift') THEN
  ALTER TABLE public.attendance_logs
    ADD CONSTRAINT fk_al_shift FOREIGN KEY (shift_id) REFERENCES public.shift_templates(id) ON DELETE SET NULL;
END IF;
END $$;


-- ----------------------------------------------------------------------------
-- SOURCE: 015_add_indexes_and_checks.sql
-- ----------------------------------------------------------------------------
-- ════════════════════════════════════════════════════════════════════
-- 015: Add missing indexes and CHECK constraints
-- Idempotent: IF NOT EXISTS for indexes, DO blocks for constraints
-- ════════════════════════════════════════════════════════════════════

-- ═══ Composite indexes for common query patterns ═══
CREATE INDEX IF NOT EXISTS idx_att_events_emp_ts ON public.attendance_events(employee_id, timestamp_utc);
CREATE INDEX IF NOT EXISTS idx_leave_req_emp_dates ON public.leave_requests(employee_id, start_date, end_date);
CREATE INDEX IF NOT EXISTS idx_payslips_batch ON public.payslips(payroll_batch_id);
CREATE INDEX IF NOT EXISTS idx_loan_ded_payslip ON public.loan_deductions(payslip_id);
CREATE INDEX IF NOT EXISTS idx_pings_emp_ts ON public.location_pings(employee_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_ts_status ON public.timesheets(status);
CREATE INDEX IF NOT EXISTS idx_notif_sent ON public.notification_logs(sent_at);
CREATE INDEX IF NOT EXISTS idx_tcr_employee ON public.task_completion_reports(employee_id);

-- ═══ CHECK constraints ═══

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'employees_role_check') THEN
  ALTER TABLE public.employees ADD CONSTRAINT employees_role_check
    CHECK (role IN ('Admin','HR Admin','Finance','Employee','Supervisor','Payroll Admin','Auditor'));
END IF;
END $$;

DO $$ BEGIN
IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'loans_type_check') THEN
  ALTER TABLE public.loans ADD CONSTRAINT loans_type_check
    CHECK (type IN ('cash_advance','salary_loan','sss','pagibig','other'));
END IF;
END $$;

