# Consolidates supabase/migrations/*.sql into supabase/migrations_v2/*.sql
# grouped by domain. SQL bodies preserved verbatim — zero behavioral drift.

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $MyInvocation.MyCommand.Path | Split-Path -Parent
$src  = Join-Path $root 'supabase\migrations'
$dst  = Join-Path $root 'supabase\migrations_v2'

if (Test-Path $dst) { Remove-Item $dst -Recurse -Force }
New-Item -ItemType Directory -Path $dst | Out-Null

# Group map: target file -> list of source migration numeric prefixes (in apply order)
$groups = [ordered]@{
  '01_auth_and_profiles.sql'        = @('001')
  '02_employees_core.sql'           = @('002','017','030','034','035','042','049','053')
  '03_roles_and_permissions.sql'    = @('003','018','059')
  '04_attendance_and_kiosk.sql'     = @('004','022','023','025','026','033','041','051')
  '05_leave.sql'                    = @('005','013','043')
  '06_payroll.sql'                  = @('006','016','024','028','036','037','038','039','045','048','054')
  '07_loans.sql'                    = @('007')
  '08_tasks_projects_messaging.sql' = @('008','010','027','029','031','032','046','060')
  '09_notifications_and_audit.sql'  = @('009','019','021','044','047','052')
  '10_government_compliance.sql'    = @('056','057','058')
  '11_storage_buckets.sql'          = @('050')
  '12_client_feature_pack.sql'      = @('055')
  '13_appearance_and_flags.sql'     = @('061')
  '14_constraints_and_indexes.sql'  = @('014','015')
  '15_rls_policies.sql'             = @('011','040')
  '16_realtime.sql'                 = @('020')
  '99_seed_data_optional.sql'       = @('012')
}

$allFiles = Get-ChildItem $src -Filter '*.sql' | Sort-Object Name
$consumed = New-Object 'System.Collections.Generic.HashSet[string]'

foreach ($entry in $groups.GetEnumerator()) {
  $outName = $entry.Key
  $prefixes = $entry.Value
  $outPath = Join-Path $dst $outName

  $header = @"
-- ============================================================================
-- $outName
-- ----------------------------------------------------------------------------
-- Consolidated from legacy migrations: $($prefixes -join ', ')
-- Apply order: run this file in the same numeric order as the file name.
-- Generated by scripts/build-migrations-v2.ps1 — DO NOT EDIT BY HAND.
-- ============================================================================

"@
  Set-Content -Path $outPath -Value $header -NoNewline -Encoding UTF8

  foreach ($p in $prefixes) {
    $match = $allFiles | Where-Object { $_.Name -like "$p`_*" } | Select-Object -First 1
    if (-not $match) { throw "No migration found for prefix $p" }
    $body = Get-Content -Path $match.FullName -Raw -Encoding UTF8
    $section = @"

-- ----------------------------------------------------------------------------
-- SOURCE: $($match.Name)
-- ----------------------------------------------------------------------------
$body

"@
    Add-Content -Path $outPath -Value $section -NoNewline -Encoding UTF8
    [void]$consumed.Add($match.Name)
  }
  Write-Host "Built $outName ($($prefixes.Count) source files)"
}

# Sanity: any unconsumed?
$missing = $allFiles | Where-Object { -not $consumed.Contains($_.Name) }
if ($missing) {
  Write-Warning "Unconsumed source migrations (not included in v2):"
  $missing | ForEach-Object { Write-Warning "  $($_.Name)" }
} else {
  Write-Host "`nAll $($allFiles.Count) source migrations consolidated into $($groups.Count) v2 files." -ForegroundColor Green
}
