import { NextRequest, NextResponse } from "next/server";
import { createServerSupabaseClient } from "@/services/supabase-server";
import { 
    getAttendanceExceptions, 
    createException, 
    resolveException, 
    updateException, 
    deleteException 
} from "@/services/attendance.service";

/**
 * GET /api/attendance/exceptions
 * 
 * Retrieves attendance exceptions, optionally filtered by employee.
 * Query params: employeeId (optional)
 */
export async function GET(request: NextRequest) {
    try {
        const supabase = await createServerSupabaseClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const { searchParams } = new URL(request.url);
        const employeeId = searchParams.get("employeeId") || undefined;

        const result = await getAttendanceExceptions(employeeId);
        if (!result.ok) {
            return NextResponse.json({ error: result.error }, { status: 500 });
        }

        return NextResponse.json({ ok: true, data: result.data });
    } catch (error) {
        console.error("[exceptions] GET error:", error);
        return NextResponse.json({ error: "Internal server error" }, { status: 500 });
    }
}

/**
 * POST /api/attendance/exceptions
 * 
 * Creates a new attendance exception.
 * Body: { employeeId, date, flag, eventId?, notes?, autoGenerated? }
 */
export async function POST(request: NextRequest) {
    try {
        const supabase = await createServerSupabaseClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const body = await request.json();
        const { employeeId, date, flag, eventId, notes, autoGenerated } = body;

        if (!employeeId || !date || !flag) {
            return NextResponse.json({ error: "Missing required fields: employeeId, date, flag" }, { status: 400 });
        }

        const validFlags = ["missing_in", "missing_out", "duplicate_scan", "out_of_geofence", "device_mismatch", "late_arrival", "early_departure", "suspicious_activity"];
        if (!validFlags.includes(flag)) {
            return NextResponse.json({ error: `Invalid flag. Must be one of: ${validFlags.join(", ")}` }, { status: 400 });
        }

        const result = await createException({
            employeeId,
            date,
            flag,
            eventId: eventId || undefined,
            notes: notes || undefined,
            autoGenerated: autoGenerated ?? false,
        });

        if (!result.ok) {
            return NextResponse.json({ error: result.error }, { status: 500 });
        }

        return NextResponse.json({ ok: true, data: result.data }, { status: 201 });
    } catch (error) {
        console.error("[exceptions] POST error:", error);
        return NextResponse.json({ error: "Internal server error" }, { status: 500 });
    }
}

/**
 * PATCH /api/attendance/exceptions
 * 
 * Updates an existing exception (edit or resolve).
 * Body: { id, action: "resolve" | "update" | "reopen", notes?, flag?, resolvedBy? }
 */
export async function PATCH(request: NextRequest) {
    try {
        const supabase = await createServerSupabaseClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const body = await request.json();
        const { id, action, notes, flag, resolvedBy } = body;

        if (!id) {
            return NextResponse.json({ error: "Missing exception id" }, { status: 400 });
        }

        if (!action || !["resolve", "update", "reopen"].includes(action)) {
            return NextResponse.json({ error: "Invalid action. Must be resolve, update, or reopen" }, { status: 400 });
        }

        let result;

        if (action === "resolve") {
            // Resolve the exception
            result = await resolveException(id, resolvedBy || user.id, notes);
        } else if (action === "reopen") {
            // Reopen a resolved exception
            result = await updateException(id, { resolvedAt: null, resolvedBy: null, notes });
        } else {
            // General update (flag, notes)
            const updates: { flag?: string; notes?: string } = {};
            if (flag) updates.flag = flag;
            if (notes !== undefined) updates.notes = notes;
            result = await updateException(id, updates);
        }

        if (!result.ok) {
            return NextResponse.json({ error: result.error }, { status: 500 });
        }

        return NextResponse.json({ ok: true, data: result.data });
    } catch (error) {
        console.error("[exceptions] PATCH error:", error);
        return NextResponse.json({ error: "Internal server error" }, { status: 500 });
    }
}

/**
 * DELETE /api/attendance/exceptions
 * 
 * Deletes an exception permanently.
 * Body: { id }
 */
export async function DELETE(request: NextRequest) {
    try {
        const supabase = await createServerSupabaseClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        const body = await request.json();
        const { id } = body;

        if (!id) {
            return NextResponse.json({ error: "Missing exception id" }, { status: 400 });
        }

        const result = await deleteException(id);
        if (!result.ok) {
            return NextResponse.json({ error: result.error }, { status: 500 });
        }

        return NextResponse.json({ ok: true });
    } catch (error) {
        console.error("[exceptions] DELETE error:", error);
        return NextResponse.json({ error: "Internal server error" }, { status: 500 });
    }
}
